// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertMatchParticipants = `-- name: InsertMatchParticipants :batchexec
INSERT INTO lol_match_participants (
    match_id, team, is_win, player_id,
    name, tag, rank_power,
    champion_id, champion_slug, champ_level, position,
    kills, deaths, assists, kda, kill_participation,
    double_kills, triple_kills, quadra_kills, penta_kills,
    gold, gold_per_min, minions_killed, neutral_minions_killed, cs, cs_per_min,
    dmg_dealt, dmg_per_min, physical_dmg_dealt, magic_dmg_dealt, true_dmg_dealt, dmg_to_turrets,
    dmg_taken, heal, heal_others, shield_others,
    vision_score, wards_placed, wards_killed,
    perf_score,
    spell1_id, spell2_id,
    rune_primary_style, rune_sub_style, key_rune, runes, stat_runes,
    items
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38,
    $39, $40, $41, $42, $43, $44, $45, $46, $47, $48
)
ON CONFLICT (match_id, player_id) DO NOTHING
`

type InsertMatchParticipantsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertMatchParticipantsParams struct {
	MatchID              string      `json:"matchId"`
	Team                 int16       `json:"team"`
	IsWin                bool        `json:"isWin"`
	PlayerID             string      `json:"playerId"`
	Name                 string      `json:"name"`
	Tag                  string      `json:"tag"`
	RankPower            pgtype.Int4 `json:"rankPower"`
	ChampionID           int32       `json:"championId"`
	ChampionSlug         string      `json:"championSlug"`
	ChampLevel           int16       `json:"champLevel"`
	Position             string      `json:"position"`
	Kills                int16       `json:"kills"`
	Deaths               int16       `json:"deaths"`
	Assists              int16       `json:"assists"`
	Kda                  float32     `json:"kda"`
	KillParticipation    float32     `json:"killParticipation"`
	DoubleKills          int16       `json:"doubleKills"`
	TripleKills          int16       `json:"tripleKills"`
	QuadraKills          int16       `json:"quadraKills"`
	PentaKills           int16       `json:"pentaKills"`
	Gold                 int32       `json:"gold"`
	GoldPerMin           float32     `json:"goldPerMin"`
	MinionsKilled        int32       `json:"minionsKilled"`
	NeutralMinionsKilled int32       `json:"neutralMinionsKilled"`
	Cs                   int32       `json:"cs"`
	CsPerMin             float32     `json:"csPerMin"`
	DmgDealt             int32       `json:"dmgDealt"`
	DmgPerMin            float32     `json:"dmgPerMin"`
	PhysicalDmgDealt     int32       `json:"physicalDmgDealt"`
	MagicDmgDealt        int32       `json:"magicDmgDealt"`
	TrueDmgDealt         int32       `json:"trueDmgDealt"`
	DmgToTurrets         int32       `json:"dmgToTurrets"`
	DmgTaken             int32       `json:"dmgTaken"`
	Heal                 int32       `json:"heal"`
	HealOthers           int32       `json:"healOthers"`
	ShieldOthers         int32       `json:"shieldOthers"`
	VisionScore          int32       `json:"visionScore"`
	WardsPlaced          int32       `json:"wardsPlaced"`
	WardsKilled          int32       `json:"wardsKilled"`
	PerfScore            int32       `json:"perfScore"`
	Spell1ID             int16       `json:"spell1Id"`
	Spell2ID             int16       `json:"spell2Id"`
	RunePrimaryStyle     int32       `json:"runePrimaryStyle"`
	RuneSubStyle         int32       `json:"runeSubStyle"`
	KeyRune              int32       `json:"keyRune"`
	Runes                []int32     `json:"runes"`
	StatRunes            []int32     `json:"statRunes"`
	Items                []int32     `json:"items"`
}

// Batch, trùng (match_id, player_id) thì bỏ qua.
func (q *Queries) InsertMatchParticipants(ctx context.Context, arg []InsertMatchParticipantsParams) *InsertMatchParticipantsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.MatchID,
			a.Team,
			a.IsWin,
			a.PlayerID,
			a.Name,
			a.Tag,
			a.RankPower,
			a.ChampionID,
			a.ChampionSlug,
			a.ChampLevel,
			a.Position,
			a.Kills,
			a.Deaths,
			a.Assists,
			a.Kda,
			a.KillParticipation,
			a.DoubleKills,
			a.TripleKills,
			a.QuadraKills,
			a.PentaKills,
			a.Gold,
			a.GoldPerMin,
			a.MinionsKilled,
			a.NeutralMinionsKilled,
			a.Cs,
			a.CsPerMin,
			a.DmgDealt,
			a.DmgPerMin,
			a.PhysicalDmgDealt,
			a.MagicDmgDealt,
			a.TrueDmgDealt,
			a.DmgToTurrets,
			a.DmgTaken,
			a.Heal,
			a.HealOthers,
			a.ShieldOthers,
			a.VisionScore,
			a.WardsPlaced,
			a.WardsKilled,
			a.PerfScore,
			a.Spell1ID,
			a.Spell2ID,
			a.RunePrimaryStyle,
			a.RuneSubStyle,
			a.KeyRune,
			a.Runes,
			a.StatRunes,
			a.Items,
		}
		batch.Queue(insertMatchParticipants, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertMatchParticipantsBatchResults{br, len(arg), false}
}

func (b *InsertMatchParticipantsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertMatchParticipantsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertMatches = `-- name: InsertMatches :batchexec
INSERT INTO lol_matches (
    id, server, mode, patch, game_start_at, duration_sec, is_remake, estimated_rank,
    banned_champion_ids,
    winning_team,
    team_1_kills, team_1_dragon_kills, team_1_herald_kills, team_1_baron_kills,
    team_2_kills, team_2_dragon_kills, team_2_herald_kills, team_2_baron_kills
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ON CONFLICT (id) DO NOTHING
`

type InsertMatchesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertMatchesParams struct {
	ID                string             `json:"id"`
	Server            string             `json:"server"`
	Mode              string             `json:"mode"`
	Patch             string             `json:"patch"`
	GameStartAt       pgtype.Timestamptz `json:"gameStartAt"`
	DurationSec       int32              `json:"durationSec"`
	IsRemake          bool               `json:"isRemake"`
	EstimatedRank     string             `json:"estimatedRank"`
	BannedChampionIds []int32            `json:"bannedChampionIds"`
	WinningTeam       int16              `json:"winningTeam"`
	Team1Kills        int16              `json:"team1Kills"`
	Team1DragonKills  int16              `json:"team1DragonKills"`
	Team1HeraldKills  int16              `json:"team1HeraldKills"`
	Team1BaronKills   int16              `json:"team1BaronKills"`
	Team2Kills        int16              `json:"team2Kills"`
	Team2DragonKills  int16              `json:"team2DragonKills"`
	Team2HeraldKills  int16              `json:"team2HeraldKills"`
	Team2BaronKills   int16              `json:"team2BaronKills"`
}

// Batch: pgx gửi cả list trong 1 round trip. Match đã kết thúc không đổi nên trùng id thì bỏ qua.
func (q *Queries) InsertMatches(ctx context.Context, arg []InsertMatchesParams) *InsertMatchesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Server,
			a.Mode,
			a.Patch,
			a.GameStartAt,
			a.DurationSec,
			a.IsRemake,
			a.EstimatedRank,
			a.BannedChampionIds,
			a.WinningTeam,
			a.Team1Kills,
			a.Team1DragonKills,
			a.Team1HeraldKills,
			a.Team1BaronKills,
			a.Team2Kills,
			a.Team2DragonKills,
			a.Team2HeraldKills,
			a.Team2BaronKills,
		}
		batch.Queue(insertMatches, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertMatchesBatchResults{br, len(arg), false}
}

func (b *InsertMatchesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertMatchesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
