// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertMatchParticipants = `-- name: InsertMatchParticipants :batchexec
INSERT INTO lol_match_participants (
    match_id, team, is_win, player_id,
    riot_name, riot_tag, rank_power,
    champion_id, champ_level, position,
    kills, deaths, assists, kda, kill_participation,
    gold_earned, minions_killed, neutral_minions_killed, cs,
    dmg_to_champs, physical_dmg_to_champs, magic_dmg_to_champs, true_dmg_to_champs, dmg_taken, vision_score,
    perf_score,
    spell1_id, spell2_id,
    rune_primary_style, rune_sub_style, key_rune, runes, stat_runes,
    items
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34
)
ON CONFLICT (match_id, player_id) DO NOTHING
`

type InsertMatchParticipantsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertMatchParticipantsParams struct {
	MatchID              string      `json:"matchId"`
	Team                 int16       `json:"team"`
	IsWin                bool        `json:"isWin"`
	PlayerID             string      `json:"playerId"`
	RiotName             string      `json:"riotName"`
	RiotTag              string      `json:"riotTag"`
	RankPower            pgtype.Int4 `json:"rankPower"`
	ChampionID           int32       `json:"championId"`
	ChampLevel           int16       `json:"champLevel"`
	Position             string      `json:"position"`
	Kills                int16       `json:"kills"`
	Deaths               int16       `json:"deaths"`
	Assists              int16       `json:"assists"`
	Kda                  float32     `json:"kda"`
	KillParticipation    float32     `json:"killParticipation"`
	GoldEarned           int32       `json:"goldEarned"`
	MinionsKilled        int32       `json:"minionsKilled"`
	NeutralMinionsKilled int32       `json:"neutralMinionsKilled"`
	Cs                   int32       `json:"cs"`
	DmgToChamps          int32       `json:"dmgToChamps"`
	PhysicalDmgToChamps  int32       `json:"physicalDmgToChamps"`
	MagicDmgToChamps     int32       `json:"magicDmgToChamps"`
	TrueDmgToChamps      int32       `json:"trueDmgToChamps"`
	DmgTaken             int32       `json:"dmgTaken"`
	VisionScore          int32       `json:"visionScore"`
	PerfScore            int32       `json:"perfScore"`
	Spell1ID             int16       `json:"spell1Id"`
	Spell2ID             int16       `json:"spell2Id"`
	RunePrimaryStyle     int32       `json:"runePrimaryStyle"`
	RuneSubStyle         int32       `json:"runeSubStyle"`
	KeyRune              int32       `json:"keyRune"`
	Runes                []int32     `json:"runes"`
	StatRunes            []int32     `json:"statRunes"`
	Items                []int32     `json:"items"`
}

// Bản batch của InsertMatchParticipant.
func (q *Queries) InsertMatchParticipants(ctx context.Context, arg []InsertMatchParticipantsParams) *InsertMatchParticipantsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.MatchID,
			a.Team,
			a.IsWin,
			a.PlayerID,
			a.RiotName,
			a.RiotTag,
			a.RankPower,
			a.ChampionID,
			a.ChampLevel,
			a.Position,
			a.Kills,
			a.Deaths,
			a.Assists,
			a.Kda,
			a.KillParticipation,
			a.GoldEarned,
			a.MinionsKilled,
			a.NeutralMinionsKilled,
			a.Cs,
			a.DmgToChamps,
			a.PhysicalDmgToChamps,
			a.MagicDmgToChamps,
			a.TrueDmgToChamps,
			a.DmgTaken,
			a.VisionScore,
			a.PerfScore,
			a.Spell1ID,
			a.Spell2ID,
			a.RunePrimaryStyle,
			a.RuneSubStyle,
			a.KeyRune,
			a.Runes,
			a.StatRunes,
			a.Items,
		}
		batch.Queue(insertMatchParticipants, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertMatchParticipantsBatchResults{br, len(arg), false}
}

func (b *InsertMatchParticipantsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertMatchParticipantsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertMatches = `-- name: InsertMatches :batchexec
INSERT INTO lol_matches (
    id, server, mode, patch, game_start_at, duration_sec, is_remake, estimated_rank,
    banned_champion_ids,
    winning_team,
    team_1_kills, team_1_dragon_kills, team_1_herald_kills, team_1_baron_kills,
    team_2_kills, team_2_dragon_kills, team_2_herald_kills, team_2_baron_kills
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ON CONFLICT (id) DO NOTHING
`

type InsertMatchesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertMatchesParams struct {
	ID                string             `json:"id"`
	Server            string             `json:"server"`
	Mode              string             `json:"mode"`
	Patch             string             `json:"patch"`
	GameStartAt       pgtype.Timestamptz `json:"gameStartAt"`
	DurationSec       int32              `json:"durationSec"`
	IsRemake          bool               `json:"isRemake"`
	EstimatedRank     pgtype.Text        `json:"estimatedRank"`
	BannedChampionIds []int32            `json:"bannedChampionIds"`
	WinningTeam       int16              `json:"winningTeam"`
	Team1Kills        int16              `json:"team1Kills"`
	Team1DragonKills  int16              `json:"team1DragonKills"`
	Team1HeraldKills  int16              `json:"team1HeraldKills"`
	Team1BaronKills   int16              `json:"team1BaronKills"`
	Team2Kills        int16              `json:"team2Kills"`
	Team2DragonKills  int16              `json:"team2DragonKills"`
	Team2HeraldKills  int16              `json:"team2HeraldKills"`
	Team2BaronKills   int16              `json:"team2BaronKills"`
}

// Bản batch của InsertMatch: pgx gửi cả list trong 1 round trip.
func (q *Queries) InsertMatches(ctx context.Context, arg []InsertMatchesParams) *InsertMatchesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Server,
			a.Mode,
			a.Patch,
			a.GameStartAt,
			a.DurationSec,
			a.IsRemake,
			a.EstimatedRank,
			a.BannedChampionIds,
			a.WinningTeam,
			a.Team1Kills,
			a.Team1DragonKills,
			a.Team1HeraldKills,
			a.Team1BaronKills,
			a.Team2Kills,
			a.Team2DragonKills,
			a.Team2HeraldKills,
			a.Team2BaronKills,
		}
		batch.Queue(insertMatches, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertMatchesBatchResults{br, len(arg), false}
}

func (b *InsertMatchesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertMatchesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
