// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Champion struct {
	ID        int32              `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Title     string             `json:"title"`
	ImgUrl    string             `json:"imgUrl"`
	Version   string             `json:"version"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Item struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Plaintext string             `json:"plaintext"`
	Type      string             `json:"type"`
	GoldTotal int32              `json:"goldTotal"`
	FromItems []int32            `json:"fromItems"`
	IntoItems []int32            `json:"intoItems"`
	IsSr      bool               `json:"isSr"`
	ImgUrl    string             `json:"imgUrl"`
	Version   string             `json:"version"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Player struct {
	ID              string             `json:"id"`
	Server          string             `json:"server"`
	Name            string             `json:"name"`
	Tag             string             `json:"tag"`
	NormalizedName  string             `json:"normalizedName"`
	NormalizedTag   string             `json:"normalizedTag"`
	ProfileIconID   pgtype.Int4        `json:"profileIconId"`
	SummonerLevel   pgtype.Int4        `json:"summonerLevel"`
	SearchString    string             `json:"searchString"`
	SoloRank        pgtype.Text        `json:"soloRank"`
	SoloTier        pgtype.Text        `json:"soloTier"`
	SoloLp          int32              `json:"soloLp"`
	SoloRankPower   pgtype.Int4        `json:"soloRankPower"`
	SoloWins        int32              `json:"soloWins"`
	SoloLosses      int32              `json:"soloLosses"`
	FlexRank        pgtype.Text        `json:"flexRank"`
	FlexTier        pgtype.Text        `json:"flexTier"`
	FlexLp          int32              `json:"flexLp"`
	FlexWins        int32              `json:"flexWins"`
	FlexLosses      int32              `json:"flexLosses"`
	LastMatchAt     pgtype.Timestamptz `json:"lastMatchAt"`
	MatchesSyncedAt pgtype.Timestamptz `json:"matchesSyncedAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}
