// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LolChampion struct {
	ID        int32              `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Title     string             `json:"title"`
	ImgUrl    string             `json:"imgUrl"`
	Skills    []byte             `json:"skills"`
	Patch     string             `json:"patch"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type LolChampionBan struct {
	MetaID     pgtype.UUID `json:"metaId"`
	ChampionID int32       `json:"championId"`
	Bans       int32       `json:"bans"`
	BanRate    float64     `json:"banRate"`
}

type LolChampionStat struct {
	MetaID               pgtype.UUID `json:"metaId"`
	Position             string      `json:"position"`
	ChampionID           int32       `json:"championId"`
	ChampionSlug         string      `json:"championSlug"`
	Games                int32       `json:"games"`
	Wins                 int32       `json:"wins"`
	WinRate              float64     `json:"winRate"`
	PickRate             float64     `json:"pickRate"`
	AvgKills             float64     `json:"avgKills"`
	AvgDeaths            float64     `json:"avgDeaths"`
	AvgAssists           float64     `json:"avgAssists"`
	AvgKda               float64     `json:"avgKda"`
	AvgKp                float64     `json:"avgKp"`
	AvgCsPerMin          float64     `json:"avgCsPerMin"`
	AvgGoldPerMin        float64     `json:"avgGoldPerMin"`
	AvgDmgPerMin         float64     `json:"avgDmgPerMin"`
	AvgDmgTakenPerMin    float64     `json:"avgDmgTakenPerMin"`
	AvgCcPerMin          float64     `json:"avgCcPerMin"`
	AvgPhysicalDmg       float64     `json:"avgPhysicalDmg"`
	AvgMagicDmg          float64     `json:"avgMagicDmg"`
	AvgTrueDmg           float64     `json:"avgTrueDmg"`
	AvgPenta             float64     `json:"avgPenta"`
	AvgSoloKills         float64     `json:"avgSoloKills"`
	AvgPerfScore         float64     `json:"avgPerfScore"`
	BestSpellCombos      []byte      `json:"bestSpellCombos"`
	BestRunes            []byte      `json:"bestRunes"`
	BestLegendaryItems   []byte      `json:"bestLegendaryItems"`
	BestBootItems        []byte      `json:"bestBootItems"`
	BestMatchUps         []byte      `json:"bestMatchUps"`
	BestStarterSets      []byte      `json:"bestStarterSets"`
	BestSkillsLeveled    []byte      `json:"bestSkillsLeveled"`
	BestFirstLegendItems []byte      `json:"bestFirstLegendItems"`
	BestFirstThreeItems  []byte      `json:"bestFirstThreeItems"`
}

type LolItem struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	Plaintext       string             `json:"plaintext"`
	Type            string             `json:"type"`
	GoldTotal       int32              `json:"goldTotal"`
	FromItems       []int32            `json:"fromItems"`
	IntoItems       []int32            `json:"intoItems"`
	IsSummonersRift bool               `json:"isSummonersRift"`
	ImgUrl          string             `json:"imgUrl"`
	Patch           string             `json:"patch"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

type LolMatch struct {
	ID                string             `json:"id"`
	Server            string             `json:"server"`
	Mode              string             `json:"mode"`
	Patch             string             `json:"patch"`
	GameStartAt       pgtype.Timestamptz `json:"gameStartAt"`
	DurationSec       int32              `json:"durationSec"`
	IsRemake          bool               `json:"isRemake"`
	EstimatedRank     string             `json:"estimatedRank"`
	BannedChampionIds []int32            `json:"bannedChampionIds"`
	WinningTeam       int16              `json:"winningTeam"`
	Team1Kills        int16              `json:"team1Kills"`
	Team1DragonKills  int16              `json:"team1DragonKills"`
	Team1HeraldKills  int16              `json:"team1HeraldKills"`
	Team1BaronKills   int16              `json:"team1BaronKills"`
	Team2Kills        int16              `json:"team2Kills"`
	Team2DragonKills  int16              `json:"team2DragonKills"`
	Team2HeraldKills  int16              `json:"team2HeraldKills"`
	Team2BaronKills   int16              `json:"team2BaronKills"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
}

type LolMatchParticipant struct {
	MatchID              string      `json:"matchId"`
	Team                 int16       `json:"team"`
	IsWin                bool        `json:"isWin"`
	PlayerID             string      `json:"playerId"`
	ParticipantID        int16       `json:"participantId"`
	Name                 string      `json:"name"`
	Tag                  string      `json:"tag"`
	RankPower            pgtype.Int4 `json:"rankPower"`
	ChampionID           int32       `json:"championId"`
	ChampionSlug         string      `json:"championSlug"`
	ChampLevel           int16       `json:"champLevel"`
	Position             string      `json:"position"`
	Kills                int16       `json:"kills"`
	Deaths               int16       `json:"deaths"`
	Assists              int16       `json:"assists"`
	Kda                  float32     `json:"kda"`
	KillParticipation    float32     `json:"killParticipation"`
	DoubleKills          int16       `json:"doubleKills"`
	TripleKills          int16       `json:"tripleKills"`
	QuadraKills          int16       `json:"quadraKills"`
	PentaKills           int16       `json:"pentaKills"`
	SoloKills            int16       `json:"soloKills"`
	Gold                 int32       `json:"gold"`
	GoldPerMin           float32     `json:"goldPerMin"`
	MinionsKilled        int32       `json:"minionsKilled"`
	NeutralMinionsKilled int32       `json:"neutralMinionsKilled"`
	Cs                   int32       `json:"cs"`
	CsPerMin             float32     `json:"csPerMin"`
	DmgDealt             int32       `json:"dmgDealt"`
	DmgPerMin            float32     `json:"dmgPerMin"`
	PhysicalDmgDealt     int32       `json:"physicalDmgDealt"`
	MagicDmgDealt        int32       `json:"magicDmgDealt"`
	TrueDmgDealt         int32       `json:"trueDmgDealt"`
	DmgToTurrets         int32       `json:"dmgToTurrets"`
	DmgTaken             int32       `json:"dmgTaken"`
	DmgTakenPerMin       float32     `json:"dmgTakenPerMin"`
	CrowdControl         int32       `json:"crowdControl"`
	CcPerMin             float32     `json:"ccPerMin"`
	Heal                 int32       `json:"heal"`
	HealOthers           int32       `json:"healOthers"`
	ShieldOthers         int32       `json:"shieldOthers"`
	VisionScore          int32       `json:"visionScore"`
	WardsPlaced          int32       `json:"wardsPlaced"`
	WardsKilled          int32       `json:"wardsKilled"`
	PerfScore            int32       `json:"perfScore"`
	Spell1ID             int16       `json:"spell1Id"`
	Spell2ID             int16       `json:"spell2Id"`
	RunePrimaryStyle     int32       `json:"runePrimaryStyle"`
	RuneSubStyle         int32       `json:"runeSubStyle"`
	KeyRune              int32       `json:"keyRune"`
	Runes                []int32     `json:"runes"`
	StatRunes            []int32     `json:"statRunes"`
	Items                []int32     `json:"items"`
	StarterSets          []int32     `json:"starterSets"`
	SkillsLeveled        []int32     `json:"skillsLeveled"`
	FirstLegendItem      int32       `json:"firstLegendItem"`
	LegendItemsPurchased []int32     `json:"legendItemsPurchased"`
}

type LolMeta struct {
	ID           pgtype.UUID        `json:"id"`
	Patch        string             `json:"patch"`
	Server       string             `json:"server"`
	RankBucket   string             `json:"rankBucket"`
	TotalMatches int32              `json:"totalMatches"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type LolPlayer struct {
	ID             string             `json:"id"`
	Server         string             `json:"server"`
	Name           string             `json:"name"`
	Tag            string             `json:"tag"`
	NormalizedName string             `json:"normalizedName"`
	NormalizedTag  string             `json:"normalizedTag"`
	ProfileIconID  pgtype.Int4        `json:"profileIconId"`
	Level          pgtype.Int4        `json:"level"`
	SearchString   string             `json:"searchString"`
	SoloRank       pgtype.Text        `json:"soloRank"`
	SoloTier       pgtype.Text        `json:"soloTier"`
	SoloLp         int32              `json:"soloLp"`
	SoloRankPower  pgtype.Int4        `json:"soloRankPower"`
	SoloWins       int32              `json:"soloWins"`
	SoloLosses     int32              `json:"soloLosses"`
	FlexRank       pgtype.Text        `json:"flexRank"`
	FlexTier       pgtype.Text        `json:"flexTier"`
	FlexLp         int32              `json:"flexLp"`
	FlexWins       int32              `json:"flexWins"`
	FlexLosses     int32              `json:"flexLosses"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type LolRune struct {
	ID        int32              `json:"id"`
	StyleID   pgtype.Int4        `json:"styleId"`
	Slot      pgtype.Int4        `json:"slot"`
	SortOrder int32              `json:"sortOrder"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	ShortDesc string             `json:"shortDesc"`
	ImgUrl    string             `json:"imgUrl"`
	Patch     string             `json:"patch"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type LolSpell struct {
	ID          int32              `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	ImgUrl      string             `json:"imgUrl"`
	Patch       string             `json:"patch"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}
