// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMatchParticipantsByMatchIds = `-- name: GetMatchParticipantsByMatchIds :many
SELECT match_id, team, is_win, player_id, name, tag, rank_power, champion_id, champion_slug, champ_level, position, kills, deaths, assists, kda, kill_participation, double_kills, triple_kills, quadra_kills, penta_kills, solo_kills, gold, gold_per_min, minions_killed, neutral_minions_killed, cs, cs_per_min, dmg_dealt, dmg_per_min, physical_dmg_dealt, magic_dmg_dealt, true_dmg_dealt, dmg_to_turrets, dmg_taken, heal, heal_others, shield_others, vision_score, wards_placed, wards_killed, perf_score, spell1_id, spell2_id, rune_primary_style, rune_sub_style, key_rune, runes, stat_runes, items FROM lol_match_participants
WHERE match_id = ANY($1::text[])
ORDER BY match_id, team, array_position(ARRAY['TOP', 'JGL', 'MID', 'ADC', 'SPT'], position), player_id
`

func (q *Queries) GetMatchParticipantsByMatchIds(ctx context.Context, matchIds []string) ([]LolMatchParticipant, error) {
	rows, err := q.db.Query(ctx, getMatchParticipantsByMatchIds, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolMatchParticipant
	for rows.Next() {
		var i LolMatchParticipant
		if err := rows.Scan(
			&i.MatchID,
			&i.Team,
			&i.IsWin,
			&i.PlayerID,
			&i.Name,
			&i.Tag,
			&i.RankPower,
			&i.ChampionID,
			&i.ChampionSlug,
			&i.ChampLevel,
			&i.Position,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.Kda,
			&i.KillParticipation,
			&i.DoubleKills,
			&i.TripleKills,
			&i.QuadraKills,
			&i.PentaKills,
			&i.SoloKills,
			&i.Gold,
			&i.GoldPerMin,
			&i.MinionsKilled,
			&i.NeutralMinionsKilled,
			&i.Cs,
			&i.CsPerMin,
			&i.DmgDealt,
			&i.DmgPerMin,
			&i.PhysicalDmgDealt,
			&i.MagicDmgDealt,
			&i.TrueDmgDealt,
			&i.DmgToTurrets,
			&i.DmgTaken,
			&i.Heal,
			&i.HealOthers,
			&i.ShieldOthers,
			&i.VisionScore,
			&i.WardsPlaced,
			&i.WardsKilled,
			&i.PerfScore,
			&i.Spell1ID,
			&i.Spell2ID,
			&i.RunePrimaryStyle,
			&i.RuneSubStyle,
			&i.KeyRune,
			&i.Runes,
			&i.StatRunes,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchesByIds = `-- name: GetMatchesByIds :many
SELECT id, server, mode, patch, game_start_at, duration_sec, is_remake, estimated_rank, banned_champion_ids, winning_team, team_1_kills, team_1_dragon_kills, team_1_herald_kills, team_1_baron_kills, team_2_kills, team_2_dragon_kills, team_2_herald_kills, team_2_baron_kills, created_at FROM lol_matches
WHERE id = ANY($1::text[])
ORDER BY game_start_at DESC
`

// Id không có trong DB thì bỏ qua.
func (q *Queries) GetMatchesByIds(ctx context.Context, ids []string) ([]LolMatch, error) {
	rows, err := q.db.Query(ctx, getMatchesByIds, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolMatch
	for rows.Next() {
		var i LolMatch
		if err := rows.Scan(
			&i.ID,
			&i.Server,
			&i.Mode,
			&i.Patch,
			&i.GameStartAt,
			&i.DurationSec,
			&i.IsRemake,
			&i.EstimatedRank,
			&i.BannedChampionIds,
			&i.WinningTeam,
			&i.Team1Kills,
			&i.Team1DragonKills,
			&i.Team1HeraldKills,
			&i.Team1BaronKills,
			&i.Team2Kills,
			&i.Team2DragonKills,
			&i.Team2HeraldKills,
			&i.Team2BaronKills,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerById = `-- name: GetPlayerById :one
SELECT id, server, name, tag, normalized_name, normalized_tag, profile_icon_id, level, search_string, solo_rank, solo_tier, solo_lp, solo_rank_power, solo_wins, solo_losses, flex_rank, flex_tier, flex_lp, flex_wins, flex_losses, created_at, updated_at FROM lol_players WHERE id = $1
`

func (q *Queries) GetPlayerById(ctx context.Context, id string) (LolPlayer, error) {
	row := q.db.QueryRow(ctx, getPlayerById, id)
	var i LolPlayer
	err := row.Scan(
		&i.ID,
		&i.Server,
		&i.Name,
		&i.Tag,
		&i.NormalizedName,
		&i.NormalizedTag,
		&i.ProfileIconID,
		&i.Level,
		&i.SearchString,
		&i.SoloRank,
		&i.SoloTier,
		&i.SoloLp,
		&i.SoloRankPower,
		&i.SoloWins,
		&i.SoloLosses,
		&i.FlexRank,
		&i.FlexTier,
		&i.FlexLp,
		&i.FlexWins,
		&i.FlexLosses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByServerNameAndTag = `-- name: GetPlayerByServerNameAndTag :one
SELECT id, server, name, tag, normalized_name, normalized_tag, profile_icon_id, level, search_string, solo_rank, solo_tier, solo_lp, solo_rank_power, solo_wins, solo_losses, flex_rank, flex_tier, flex_lp, flex_wins, flex_losses, created_at, updated_at FROM lol_players WHERE server = $1 AND normalized_name = $2 AND normalized_tag = $3
`

type GetPlayerByServerNameAndTagParams struct {
	Server         string `json:"server"`
	NormalizedName string `json:"normalizedName"`
	NormalizedTag  string `json:"normalizedTag"`
}

// Truyền vào name / tag đã normalize (chữ thường + trim).
func (q *Queries) GetPlayerByServerNameAndTag(ctx context.Context, arg GetPlayerByServerNameAndTagParams) (LolPlayer, error) {
	row := q.db.QueryRow(ctx, getPlayerByServerNameAndTag, arg.Server, arg.NormalizedName, arg.NormalizedTag)
	var i LolPlayer
	err := row.Scan(
		&i.ID,
		&i.Server,
		&i.Name,
		&i.Tag,
		&i.NormalizedName,
		&i.NormalizedTag,
		&i.ProfileIconID,
		&i.Level,
		&i.SearchString,
		&i.SoloRank,
		&i.SoloTier,
		&i.SoloLp,
		&i.SoloRankPower,
		&i.SoloWins,
		&i.SoloLosses,
		&i.FlexRank,
		&i.FlexTier,
		&i.FlexLp,
		&i.FlexWins,
		&i.FlexLosses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayersByIds = `-- name: GetPlayersByIds :many
SELECT id, server, name, tag, normalized_name, normalized_tag, profile_icon_id, level, search_string, solo_rank, solo_tier, solo_lp, solo_rank_power, solo_wins, solo_losses, flex_rank, flex_tier, flex_lp, flex_wins, flex_losses, created_at, updated_at FROM lol_players WHERE id = ANY($1::text[])
`

// Id không có trong DB thì bỏ qua.
func (q *Queries) GetPlayersByIds(ctx context.Context, ids []string) ([]LolPlayer, error) {
	rows, err := q.db.Query(ctx, getPlayersByIds, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolPlayer
	for rows.Next() {
		var i LolPlayer
		if err := rows.Scan(
			&i.ID,
			&i.Server,
			&i.Name,
			&i.Tag,
			&i.NormalizedName,
			&i.NormalizedTag,
			&i.ProfileIconID,
			&i.Level,
			&i.SearchString,
			&i.SoloRank,
			&i.SoloTier,
			&i.SoloLp,
			&i.SoloRankPower,
			&i.SoloWins,
			&i.SoloLosses,
			&i.FlexRank,
			&i.FlexTier,
			&i.FlexLp,
			&i.FlexWins,
			&i.FlexLosses,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChampions = `-- name: ListChampions :many
SELECT id, slug, name, title, img_url, patch, updated_at FROM lol_champions ORDER BY name
`

func (q *Queries) ListChampions(ctx context.Context) ([]LolChampion, error) {
	rows, err := q.db.Query(ctx, listChampions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolChampion
	for rows.Next() {
		var i LolChampion
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Title,
			&i.ImgUrl,
			&i.Patch,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, name, plaintext, type, gold_total, from_items, into_items, is_summoners_rift, img_url, patch, updated_at FROM lol_items ORDER BY id
`

func (q *Queries) ListItems(ctx context.Context) ([]LolItem, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolItem
	for rows.Next() {
		var i LolItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Plaintext,
			&i.Type,
			&i.GoldTotal,
			&i.FromItems,
			&i.IntoItems,
			&i.IsSummonersRift,
			&i.ImgUrl,
			&i.Patch,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunes = `-- name: ListRunes :many
SELECT id, style_id, slot, slug, name, short_desc, img_url, patch, updated_at FROM lol_runes ORDER BY style_id NULLS FIRST, slot, id
`

// Cây trước, rồi tới rune của từng cây theo đúng thứ tự hàng.
func (q *Queries) ListRunes(ctx context.Context) ([]LolRune, error) {
	rows, err := q.db.Query(ctx, listRunes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolRune
	for rows.Next() {
		var i LolRune
		if err := rows.Scan(
			&i.ID,
			&i.StyleID,
			&i.Slot,
			&i.Slug,
			&i.Name,
			&i.ShortDesc,
			&i.ImgUrl,
			&i.Patch,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpells = `-- name: ListSpells :many
SELECT id, slug, name, description, img_url, patch, updated_at FROM lol_spells ORDER BY id
`

func (q *Queries) ListSpells(ctx context.Context) ([]LolSpell, error) {
	rows, err := q.db.Query(ctx, listSpells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolSpell
	for rows.Next() {
		var i LolSpell
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ImgUrl,
			&i.Patch,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlayers = `-- name: SearchPlayers :many
SELECT id, server, name, tag, normalized_name, normalized_tag, profile_icon_id, level, search_string, solo_rank, solo_tier, solo_lp, solo_rank_power, solo_wins, solo_losses, flex_rank, flex_tier, flex_lp, flex_wins, flex_losses, created_at, updated_at FROM lol_players
WHERE name ILIKE '%' || $1::text || '%'
   OR tag ILIKE '%' || $1::text || '%'
   OR search_string LIKE '%' || $2::text || '%'
ORDER BY solo_rank_power DESC NULLS LAST
LIMIT $3
`

type SearchPlayersParams struct {
	Keyword           string `json:"keyword"`
	NormalizedKeyword string `json:"normalizedKeyword"`
	Lim               int32  `json:"lim"`
}

func (q *Queries) SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]LolPlayer, error) {
	rows, err := q.db.Query(ctx, searchPlayers, arg.Keyword, arg.NormalizedKeyword, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolPlayer
	for rows.Next() {
		var i LolPlayer
		if err := rows.Scan(
			&i.ID,
			&i.Server,
			&i.Name,
			&i.Tag,
			&i.NormalizedName,
			&i.NormalizedTag,
			&i.ProfileIconID,
			&i.Level,
			&i.SearchString,
			&i.SoloRank,
			&i.SoloTier,
			&i.SoloLp,
			&i.SoloRankPower,
			&i.SoloWins,
			&i.SoloLosses,
			&i.FlexRank,
			&i.FlexTier,
			&i.FlexLp,
			&i.FlexWins,
			&i.FlexLosses,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChampion = `-- name: UpsertChampion :exec
INSERT INTO lol_champions (id, slug, name, title, img_url, patch)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    slug       = EXCLUDED.slug,
    name       = EXCLUDED.name,
    title      = EXCLUDED.title,
    img_url    = EXCLUDED.img_url,
    patch      = EXCLUDED.patch,
    updated_at = now()
`

type UpsertChampionParams struct {
	ID     int32  `json:"id"`
	Slug   string `json:"slug"`
	Name   string `json:"name"`
	Title  string `json:"title"`
	ImgUrl string `json:"imgUrl"`
	Patch  string `json:"patch"`
}

func (q *Queries) UpsertChampion(ctx context.Context, arg UpsertChampionParams) error {
	_, err := q.db.Exec(ctx, upsertChampion,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Title,
		arg.ImgUrl,
		arg.Patch,
	)
	return err
}

const upsertItem = `-- name: UpsertItem :exec
INSERT INTO lol_items (id, name, plaintext, type, gold_total, from_items, into_items, is_summoners_rift, img_url, patch)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
    name       = EXCLUDED.name,
    plaintext  = EXCLUDED.plaintext,
    type       = EXCLUDED.type,
    gold_total = EXCLUDED.gold_total,
    from_items = EXCLUDED.from_items,
    into_items = EXCLUDED.into_items,
    is_summoners_rift = EXCLUDED.is_summoners_rift,
    img_url    = EXCLUDED.img_url,
    patch      = EXCLUDED.patch,
    updated_at = now()
`

type UpsertItemParams struct {
	ID              int32   `json:"id"`
	Name            string  `json:"name"`
	Plaintext       string  `json:"plaintext"`
	Type            string  `json:"type"`
	GoldTotal       int32   `json:"goldTotal"`
	FromItems       []int32 `json:"fromItems"`
	IntoItems       []int32 `json:"intoItems"`
	IsSummonersRift bool    `json:"isSummonersRift"`
	ImgUrl          string  `json:"imgUrl"`
	Patch           string  `json:"patch"`
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) error {
	_, err := q.db.Exec(ctx, upsertItem,
		arg.ID,
		arg.Name,
		arg.Plaintext,
		arg.Type,
		arg.GoldTotal,
		arg.FromItems,
		arg.IntoItems,
		arg.IsSummonersRift,
		arg.ImgUrl,
		arg.Patch,
	)
	return err
}

const upsertPlayer = `-- name: UpsertPlayer :exec
INSERT INTO lol_players (
    id, server, name, tag, normalized_name, normalized_tag, profile_icon_id, level, search_string,
    solo_rank, solo_tier, solo_lp, solo_rank_power, solo_wins, solo_losses,
    flex_rank, flex_tier, flex_lp, flex_wins, flex_losses
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
ON CONFLICT (id) DO UPDATE SET
    server          = EXCLUDED.server,
    name            = EXCLUDED.name,
    tag             = EXCLUDED.tag,
    normalized_name = EXCLUDED.normalized_name,
    normalized_tag  = EXCLUDED.normalized_tag,
    profile_icon_id = COALESCE(EXCLUDED.profile_icon_id, lol_players.profile_icon_id),
    level           = COALESCE(EXCLUDED.level, lol_players.level),
    search_string   = EXCLUDED.search_string,

    solo_rank       = COALESCE(EXCLUDED.solo_rank, lol_players.solo_rank),
    solo_tier       = CASE WHEN EXCLUDED.solo_rank IS NULL THEN lol_players.solo_tier       ELSE EXCLUDED.solo_tier       END,
    solo_lp         = CASE WHEN EXCLUDED.solo_rank IS NULL THEN lol_players.solo_lp         ELSE EXCLUDED.solo_lp         END,
    solo_rank_power = CASE WHEN EXCLUDED.solo_rank IS NULL THEN lol_players.solo_rank_power ELSE EXCLUDED.solo_rank_power END,
    solo_wins       = CASE WHEN EXCLUDED.solo_rank IS NULL THEN lol_players.solo_wins       ELSE EXCLUDED.solo_wins       END,
    solo_losses     = CASE WHEN EXCLUDED.solo_rank IS NULL THEN lol_players.solo_losses     ELSE EXCLUDED.solo_losses     END,

    flex_rank       = COALESCE(EXCLUDED.flex_rank, lol_players.flex_rank),
    flex_tier       = CASE WHEN EXCLUDED.flex_rank IS NULL THEN lol_players.flex_tier   ELSE EXCLUDED.flex_tier   END,
    flex_lp         = CASE WHEN EXCLUDED.flex_rank IS NULL THEN lol_players.flex_lp     ELSE EXCLUDED.flex_lp     END,
    flex_wins       = CASE WHEN EXCLUDED.flex_rank IS NULL THEN lol_players.flex_wins   ELSE EXCLUDED.flex_wins   END,
    flex_losses     = CASE WHEN EXCLUDED.flex_rank IS NULL THEN lol_players.flex_losses ELSE EXCLUDED.flex_losses END,

    updated_at      = now()
`

type UpsertPlayerParams struct {
	ID             string      `json:"id"`
	Server         string      `json:"server"`
	Name           string      `json:"name"`
	Tag            string      `json:"tag"`
	NormalizedName string      `json:"normalizedName"`
	NormalizedTag  string      `json:"normalizedTag"`
	ProfileIconID  pgtype.Int4 `json:"profileIconId"`
	Level          pgtype.Int4 `json:"level"`
	SearchString   string      `json:"searchString"`
	SoloRank       pgtype.Text `json:"soloRank"`
	SoloTier       pgtype.Text `json:"soloTier"`
	SoloLp         int32       `json:"soloLp"`
	SoloRankPower  pgtype.Int4 `json:"soloRankPower"`
	SoloWins       int32       `json:"soloWins"`
	SoloLosses     int32       `json:"soloLosses"`
	FlexRank       pgtype.Text `json:"flexRank"`
	FlexTier       pgtype.Text `json:"flexTier"`
	FlexLp         int32       `json:"flexLp"`
	FlexWins       int32       `json:"flexWins"`
	FlexLosses     int32       `json:"flexLosses"`
}

// Rank solo/flex truyền vào NULL (unknown) thì giữ nguyên cả nhóm cột rank cũ.
func (q *Queries) UpsertPlayer(ctx context.Context, arg UpsertPlayerParams) error {
	_, err := q.db.Exec(ctx, upsertPlayer,
		arg.ID,
		arg.Server,
		arg.Name,
		arg.Tag,
		arg.NormalizedName,
		arg.NormalizedTag,
		arg.ProfileIconID,
		arg.Level,
		arg.SearchString,
		arg.SoloRank,
		arg.SoloTier,
		arg.SoloLp,
		arg.SoloRankPower,
		arg.SoloWins,
		arg.SoloLosses,
		arg.FlexRank,
		arg.FlexTier,
		arg.FlexLp,
		arg.FlexWins,
		arg.FlexLosses,
	)
	return err
}

const upsertRune = `-- name: UpsertRune :exec
INSERT INTO lol_runes (id, style_id, slot, slug, name, short_desc, img_url, patch)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    style_id   = EXCLUDED.style_id,
    slot       = EXCLUDED.slot,
    slug       = EXCLUDED.slug,
    name       = EXCLUDED.name,
    short_desc = EXCLUDED.short_desc,
    img_url    = EXCLUDED.img_url,
    patch      = EXCLUDED.patch,
    updated_at = now()
`

type UpsertRuneParams struct {
	ID        int32       `json:"id"`
	StyleID   pgtype.Int4 `json:"styleId"`
	Slot      pgtype.Int4 `json:"slot"`
	Slug      string      `json:"slug"`
	Name      string      `json:"name"`
	ShortDesc string      `json:"shortDesc"`
	ImgUrl    string      `json:"imgUrl"`
	Patch     string      `json:"patch"`
}

// Cây (style_id NULL) phải upsert trước rune của nó vì style_id tham chiếu ngược về chính bảng này.
func (q *Queries) UpsertRune(ctx context.Context, arg UpsertRuneParams) error {
	_, err := q.db.Exec(ctx, upsertRune,
		arg.ID,
		arg.StyleID,
		arg.Slot,
		arg.Slug,
		arg.Name,
		arg.ShortDesc,
		arg.ImgUrl,
		arg.Patch,
	)
	return err
}

const upsertSpell = `-- name: UpsertSpell :exec
INSERT INTO lol_spells (id, slug, name, description, img_url, patch)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    slug        = EXCLUDED.slug,
    name        = EXCLUDED.name,
    description = EXCLUDED.description,
    img_url     = EXCLUDED.img_url,
    patch       = EXCLUDED.patch,
    updated_at  = now()
`

type UpsertSpellParams struct {
	ID          int32  `json:"id"`
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
	ImgUrl      string `json:"imgUrl"`
	Patch       string `json:"patch"`
}

func (q *Queries) UpsertSpell(ctx context.Context, arg UpsertSpellParams) error {
	_, err := q.db.Exec(ctx, upsertSpell,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ImgUrl,
		arg.Patch,
	)
	return err
}
