// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSliceMatches = `-- name: CountSliceMatches :one

SELECT count(*) FROM lol_matches m
WHERE m.patch = $1::text
  AND m.mode = 'SOLO'
  AND NOT m.is_remake
  AND m.duration_sec >= $2::int
  AND m.estimated_rank = ANY($3::text[])
  AND ($4::text = 'GLOBAL' OR m.server = $4::text)
`

type CountSliceMatchesParams struct {
	Patch       string   `json:"patch"`
	MinDuration int32    `json:"minDuration"`
	Ranks       []string `json:"ranks"`
	Server      string   `json:"server"`
}

// ============================================================
// ANALYTICS
// Lọc match hợp lệ của 1 lát cắt luôn cùng bộ điều kiện: patch + mode ranked +
// không remake + đủ dài + đúng rank bucket + (GLOBAL hoặc đúng server).
// ============================================================
func (q *Queries) CountSliceMatches(ctx context.Context, arg CountSliceMatchesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSliceMatches,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChampionBansByMeta = `-- name: DeleteChampionBansByMeta :exec
DELETE FROM lol_champion_bans WHERE meta_id = $1::uuid
`

func (q *Queries) DeleteChampionBansByMeta(ctx context.Context, metaID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChampionBansByMeta, metaID)
	return err
}

const deleteChampionStatsByMeta = `-- name: DeleteChampionStatsByMeta :exec
DELETE FROM lol_champion_stats WHERE meta_id = $1::uuid
`

func (q *Queries) DeleteChampionStatsByMeta(ctx context.Context, metaID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChampionStatsByMeta, metaID)
	return err
}

const getChampionStatsByMeta = `-- name: GetChampionStatsByMeta :many
SELECT cs.meta_id, cs.position, cs.champion_id, cs.champion_slug,
       cs.games, cs.wins, cs.win_rate, cs.pick_rate,
       cs.avg_kills, cs.avg_deaths, cs.avg_assists, cs.avg_kda, cs.avg_kp,
       cs.avg_cs_per_min, cs.avg_gold_per_min, cs.avg_dmg_per_min, cs.avg_dmg_taken_per_min, cs.avg_cc_per_min,
       cs.avg_physical_dmg, cs.avg_magic_dmg, cs.avg_true_dmg,
       cs.avg_penta, cs.avg_solo_kills, cs.avg_perf_score,
       cs.best_match_ups,
       COALESCE(b.bans, 0)::int AS bans, COALESCE(b.ban_rate, 0)::float8 AS ban_rate
FROM lol_champion_stats cs
LEFT JOIN lol_champion_bans b ON b.meta_id = cs.meta_id AND b.champion_id = cs.champion_id
WHERE cs.meta_id = $1::uuid
ORDER BY array_position(ARRAY['TOP', 'JGL', 'MID', 'ADC', 'SPT'], cs.position), cs.games DESC
`

type GetChampionStatsByMetaRow struct {
	MetaID            pgtype.UUID `json:"metaId"`
	Position          string      `json:"position"`
	ChampionID        int32       `json:"championId"`
	ChampionSlug      string      `json:"championSlug"`
	Games             int32       `json:"games"`
	Wins              int32       `json:"wins"`
	WinRate           float64     `json:"winRate"`
	PickRate          float64     `json:"pickRate"`
	AvgKills          float64     `json:"avgKills"`
	AvgDeaths         float64     `json:"avgDeaths"`
	AvgAssists        float64     `json:"avgAssists"`
	AvgKda            float64     `json:"avgKda"`
	AvgKp             float64     `json:"avgKp"`
	AvgCsPerMin       float64     `json:"avgCsPerMin"`
	AvgGoldPerMin     float64     `json:"avgGoldPerMin"`
	AvgDmgPerMin      float64     `json:"avgDmgPerMin"`
	AvgDmgTakenPerMin float64     `json:"avgDmgTakenPerMin"`
	AvgCcPerMin       float64     `json:"avgCcPerMin"`
	AvgPhysicalDmg    float64     `json:"avgPhysicalDmg"`
	AvgMagicDmg       float64     `json:"avgMagicDmg"`
	AvgTrueDmg        float64     `json:"avgTrueDmg"`
	AvgPenta          float64     `json:"avgPenta"`
	AvgSoloKills      float64     `json:"avgSoloKills"`
	AvgPerfScore      float64     `json:"avgPerfScore"`
	BestMatchUps      []byte      `json:"bestMatchUps"`
	Bans              int32       `json:"bans"`
	BanRate           float64     `json:"banRate"`
}

// Tier list: cột scalar + best_match_ups, KHÔNG lấy các cột JSONB build còn lại (chúng chiếm
// ~85% payload của cả meta mà tier list không dùng tới); muốn build thì gọi
// GetChampionStatsByMetaAndChampId cho từng tướng.
func (q *Queries) GetChampionStatsByMeta(ctx context.Context, metaID pgtype.UUID) ([]GetChampionStatsByMetaRow, error) {
	rows, err := q.db.Query(ctx, getChampionStatsByMeta, metaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChampionStatsByMetaRow
	for rows.Next() {
		var i GetChampionStatsByMetaRow
		if err := rows.Scan(
			&i.MetaID,
			&i.Position,
			&i.ChampionID,
			&i.ChampionSlug,
			&i.Games,
			&i.Wins,
			&i.WinRate,
			&i.PickRate,
			&i.AvgKills,
			&i.AvgDeaths,
			&i.AvgAssists,
			&i.AvgKda,
			&i.AvgKp,
			&i.AvgCsPerMin,
			&i.AvgGoldPerMin,
			&i.AvgDmgPerMin,
			&i.AvgDmgTakenPerMin,
			&i.AvgCcPerMin,
			&i.AvgPhysicalDmg,
			&i.AvgMagicDmg,
			&i.AvgTrueDmg,
			&i.AvgPenta,
			&i.AvgSoloKills,
			&i.AvgPerfScore,
			&i.BestMatchUps,
			&i.Bans,
			&i.BanRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChampionStatsByMetaAndChampId = `-- name: GetChampionStatsByMetaAndChampId :many
SELECT cs.meta_id, cs.position, cs.champion_id, cs.champion_slug, cs.games, cs.wins, cs.win_rate, cs.pick_rate, cs.avg_kills, cs.avg_deaths, cs.avg_assists, cs.avg_kda, cs.avg_kp, cs.avg_cs_per_min, cs.avg_gold_per_min, cs.avg_dmg_per_min, cs.avg_dmg_taken_per_min, cs.avg_cc_per_min, cs.avg_physical_dmg, cs.avg_magic_dmg, cs.avg_true_dmg, cs.avg_penta, cs.avg_solo_kills, cs.avg_perf_score, cs.best_spell_combos, cs.best_runes, cs.best_legendary_items, cs.best_boot_items, cs.best_match_ups, cs.best_starter_sets, cs.best_skills_leveled, cs.best_first_legend_items, cs.best_first_three_items, COALESCE(b.bans, 0)::int AS bans, COALESCE(b.ban_rate, 0)::float8 AS ban_rate
FROM lol_champion_stats cs
LEFT JOIN lol_champion_bans b ON b.meta_id = cs.meta_id AND b.champion_id = cs.champion_id
WHERE cs.meta_id = $1::uuid
  AND cs.champion_id = $2::int
ORDER BY array_position(ARRAY['TOP', 'JGL', 'MID', 'ADC', 'SPT'], cs.position), cs.games DESC
`

type GetChampionStatsByMetaAndChampIdParams struct {
	MetaID     pgtype.UUID `json:"metaId"`
	ChampionID int32       `json:"championId"`
}

type GetChampionStatsByMetaAndChampIdRow struct {
	MetaID               pgtype.UUID `json:"metaId"`
	Position             string      `json:"position"`
	ChampionID           int32       `json:"championId"`
	ChampionSlug         string      `json:"championSlug"`
	Games                int32       `json:"games"`
	Wins                 int32       `json:"wins"`
	WinRate              float64     `json:"winRate"`
	PickRate             float64     `json:"pickRate"`
	AvgKills             float64     `json:"avgKills"`
	AvgDeaths            float64     `json:"avgDeaths"`
	AvgAssists           float64     `json:"avgAssists"`
	AvgKda               float64     `json:"avgKda"`
	AvgKp                float64     `json:"avgKp"`
	AvgCsPerMin          float64     `json:"avgCsPerMin"`
	AvgGoldPerMin        float64     `json:"avgGoldPerMin"`
	AvgDmgPerMin         float64     `json:"avgDmgPerMin"`
	AvgDmgTakenPerMin    float64     `json:"avgDmgTakenPerMin"`
	AvgCcPerMin          float64     `json:"avgCcPerMin"`
	AvgPhysicalDmg       float64     `json:"avgPhysicalDmg"`
	AvgMagicDmg          float64     `json:"avgMagicDmg"`
	AvgTrueDmg           float64     `json:"avgTrueDmg"`
	AvgPenta             float64     `json:"avgPenta"`
	AvgSoloKills         float64     `json:"avgSoloKills"`
	AvgPerfScore         float64     `json:"avgPerfScore"`
	BestSpellCombos      []byte      `json:"bestSpellCombos"`
	BestRunes            []byte      `json:"bestRunes"`
	BestLegendaryItems   []byte      `json:"bestLegendaryItems"`
	BestBootItems        []byte      `json:"bestBootItems"`
	BestMatchUps         []byte      `json:"bestMatchUps"`
	BestStarterSets      []byte      `json:"bestStarterSets"`
	BestSkillsLeveled    []byte      `json:"bestSkillsLeveled"`
	BestFirstLegendItems []byte      `json:"bestFirstLegendItems"`
	BestFirstThreeItems  []byte      `json:"bestFirstThreeItems"`
	Bans                 int32       `json:"bans"`
	BanRate              float64     `json:"banRate"`
}

// Như trên nhưng chỉ 1 tướng (mọi position của nó), và có kèm build.
func (q *Queries) GetChampionStatsByMetaAndChampId(ctx context.Context, arg GetChampionStatsByMetaAndChampIdParams) ([]GetChampionStatsByMetaAndChampIdRow, error) {
	rows, err := q.db.Query(ctx, getChampionStatsByMetaAndChampId, arg.MetaID, arg.ChampionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChampionStatsByMetaAndChampIdRow
	for rows.Next() {
		var i GetChampionStatsByMetaAndChampIdRow
		if err := rows.Scan(
			&i.MetaID,
			&i.Position,
			&i.ChampionID,
			&i.ChampionSlug,
			&i.Games,
			&i.Wins,
			&i.WinRate,
			&i.PickRate,
			&i.AvgKills,
			&i.AvgDeaths,
			&i.AvgAssists,
			&i.AvgKda,
			&i.AvgKp,
			&i.AvgCsPerMin,
			&i.AvgGoldPerMin,
			&i.AvgDmgPerMin,
			&i.AvgDmgTakenPerMin,
			&i.AvgCcPerMin,
			&i.AvgPhysicalDmg,
			&i.AvgMagicDmg,
			&i.AvgTrueDmg,
			&i.AvgPenta,
			&i.AvgSoloKills,
			&i.AvgPerfScore,
			&i.BestSpellCombos,
			&i.BestRunes,
			&i.BestLegendaryItems,
			&i.BestBootItems,
			&i.BestMatchUps,
			&i.BestStarterSets,
			&i.BestSkillsLeveled,
			&i.BestFirstLegendItems,
			&i.BestFirstThreeItems,
			&i.Bans,
			&i.BanRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchParticipantsByMatchIds = `-- name: GetMatchParticipantsByMatchIds :many
SELECT match_id, team, is_win, player_id, participant_id, name, tag, rank_power, champion_id, champion_slug, champ_level, position, kills, deaths, assists, kda, kill_participation, double_kills, triple_kills, quadra_kills, penta_kills, solo_kills, gold, gold_per_min, minions_killed, neutral_minions_killed, cs, cs_per_min, dmg_dealt, dmg_per_min, physical_dmg_dealt, magic_dmg_dealt, true_dmg_dealt, dmg_to_turrets, dmg_taken, dmg_taken_per_min, crowd_control, cc_per_min, heal, heal_others, shield_others, vision_score, wards_placed, wards_killed, perf_score, spell1_id, spell2_id, rune_primary_style, rune_sub_style, key_rune, runes, stat_runes, items, role_bound_item, starter_sets, skills_leveled, first_legend_item, legend_items_purchased FROM lol_match_participants
WHERE match_id = ANY($1::text[])
ORDER BY match_id, team, array_position(ARRAY['TOP', 'JGL', 'MID', 'ADC', 'SPT'], position), player_id
`

func (q *Queries) GetMatchParticipantsByMatchIds(ctx context.Context, matchIds []string) ([]LolMatchParticipant, error) {
	rows, err := q.db.Query(ctx, getMatchParticipantsByMatchIds, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolMatchParticipant
	for rows.Next() {
		var i LolMatchParticipant
		if err := rows.Scan(
			&i.MatchID,
			&i.Team,
			&i.IsWin,
			&i.PlayerID,
			&i.ParticipantID,
			&i.Name,
			&i.Tag,
			&i.RankPower,
			&i.ChampionID,
			&i.ChampionSlug,
			&i.ChampLevel,
			&i.Position,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.Kda,
			&i.KillParticipation,
			&i.DoubleKills,
			&i.TripleKills,
			&i.QuadraKills,
			&i.PentaKills,
			&i.SoloKills,
			&i.Gold,
			&i.GoldPerMin,
			&i.MinionsKilled,
			&i.NeutralMinionsKilled,
			&i.Cs,
			&i.CsPerMin,
			&i.DmgDealt,
			&i.DmgPerMin,
			&i.PhysicalDmgDealt,
			&i.MagicDmgDealt,
			&i.TrueDmgDealt,
			&i.DmgToTurrets,
			&i.DmgTaken,
			&i.DmgTakenPerMin,
			&i.CrowdControl,
			&i.CcPerMin,
			&i.Heal,
			&i.HealOthers,
			&i.ShieldOthers,
			&i.VisionScore,
			&i.WardsPlaced,
			&i.WardsKilled,
			&i.PerfScore,
			&i.Spell1ID,
			&i.Spell2ID,
			&i.RunePrimaryStyle,
			&i.RuneSubStyle,
			&i.KeyRune,
			&i.Runes,
			&i.StatRunes,
			&i.Items,
			&i.RoleBoundItem,
			&i.StarterSets,
			&i.SkillsLeveled,
			&i.FirstLegendItem,
			&i.LegendItemsPurchased,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchesByIds = `-- name: GetMatchesByIds :many
SELECT id, server, mode, patch, game_start_at, duration_sec, is_remake, estimated_rank, banned_champion_ids, winning_team, team_1_kills, team_1_dragon_kills, team_1_herald_kills, team_1_baron_kills, team_2_kills, team_2_dragon_kills, team_2_herald_kills, team_2_baron_kills, created_at FROM lol_matches
WHERE id = ANY($1::text[])
ORDER BY game_start_at DESC
`

// Id không có trong DB thì bỏ qua.
func (q *Queries) GetMatchesByIds(ctx context.Context, ids []string) ([]LolMatch, error) {
	rows, err := q.db.Query(ctx, getMatchesByIds, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolMatch
	for rows.Next() {
		var i LolMatch
		if err := rows.Scan(
			&i.ID,
			&i.Server,
			&i.Mode,
			&i.Patch,
			&i.GameStartAt,
			&i.DurationSec,
			&i.IsRemake,
			&i.EstimatedRank,
			&i.BannedChampionIds,
			&i.WinningTeam,
			&i.Team1Kills,
			&i.Team1DragonKills,
			&i.Team1HeraldKills,
			&i.Team1BaronKills,
			&i.Team2Kills,
			&i.Team2DragonKills,
			&i.Team2HeraldKills,
			&i.Team2BaronKills,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeta = `-- name: GetMeta :one
SELECT id, patch, server, rank_bucket, total_matches, updated_at FROM lol_metas
WHERE patch = $1::text AND server = $2::text AND rank_bucket = $3::text
`

type GetMetaParams struct {
	Patch      string `json:"patch"`
	Server     string `json:"server"`
	RankBucket string `json:"rankBucket"`
}

func (q *Queries) GetMeta(ctx context.Context, arg GetMetaParams) (LolMeta, error) {
	row := q.db.QueryRow(ctx, getMeta, arg.Patch, arg.Server, arg.RankBucket)
	var i LolMeta
	err := row.Scan(
		&i.ID,
		&i.Patch,
		&i.Server,
		&i.RankBucket,
		&i.TotalMatches,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerById = `-- name: GetPlayerById :one
SELECT id, server, name, tag, normalized_name, normalized_tag, profile_icon_id, level, search_string, solo_rank, solo_tier, solo_lp, solo_rank_power, solo_wins, solo_losses, flex_rank, flex_tier, flex_lp, flex_wins, flex_losses, created_at, updated_at FROM lol_players WHERE id = $1
`

func (q *Queries) GetPlayerById(ctx context.Context, id string) (LolPlayer, error) {
	row := q.db.QueryRow(ctx, getPlayerById, id)
	var i LolPlayer
	err := row.Scan(
		&i.ID,
		&i.Server,
		&i.Name,
		&i.Tag,
		&i.NormalizedName,
		&i.NormalizedTag,
		&i.ProfileIconID,
		&i.Level,
		&i.SearchString,
		&i.SoloRank,
		&i.SoloTier,
		&i.SoloLp,
		&i.SoloRankPower,
		&i.SoloWins,
		&i.SoloLosses,
		&i.FlexRank,
		&i.FlexTier,
		&i.FlexLp,
		&i.FlexWins,
		&i.FlexLosses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByServerNameAndTag = `-- name: GetPlayerByServerNameAndTag :one
SELECT id, server, name, tag, normalized_name, normalized_tag, profile_icon_id, level, search_string, solo_rank, solo_tier, solo_lp, solo_rank_power, solo_wins, solo_losses, flex_rank, flex_tier, flex_lp, flex_wins, flex_losses, created_at, updated_at FROM lol_players WHERE server = $1 AND normalized_name = $2 AND normalized_tag = $3
`

type GetPlayerByServerNameAndTagParams struct {
	Server         string `json:"server"`
	NormalizedName string `json:"normalizedName"`
	NormalizedTag  string `json:"normalizedTag"`
}

// Truyền vào name / tag đã normalize (chữ thường + trim).
func (q *Queries) GetPlayerByServerNameAndTag(ctx context.Context, arg GetPlayerByServerNameAndTagParams) (LolPlayer, error) {
	row := q.db.QueryRow(ctx, getPlayerByServerNameAndTag, arg.Server, arg.NormalizedName, arg.NormalizedTag)
	var i LolPlayer
	err := row.Scan(
		&i.ID,
		&i.Server,
		&i.Name,
		&i.Tag,
		&i.NormalizedName,
		&i.NormalizedTag,
		&i.ProfileIconID,
		&i.Level,
		&i.SearchString,
		&i.SoloRank,
		&i.SoloTier,
		&i.SoloLp,
		&i.SoloRankPower,
		&i.SoloWins,
		&i.SoloLosses,
		&i.FlexRank,
		&i.FlexTier,
		&i.FlexLp,
		&i.FlexWins,
		&i.FlexLosses,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayersByIds = `-- name: GetPlayersByIds :many
SELECT id, server, name, tag, normalized_name, normalized_tag, profile_icon_id, level, search_string, solo_rank, solo_tier, solo_lp, solo_rank_power, solo_wins, solo_losses, flex_rank, flex_tier, flex_lp, flex_wins, flex_losses, created_at, updated_at FROM lol_players WHERE id = ANY($1::text[])
`

// Id không có trong DB thì bỏ qua.
func (q *Queries) GetPlayersByIds(ctx context.Context, ids []string) ([]LolPlayer, error) {
	rows, err := q.db.Query(ctx, getPlayersByIds, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolPlayer
	for rows.Next() {
		var i LolPlayer
		if err := rows.Scan(
			&i.ID,
			&i.Server,
			&i.Name,
			&i.Tag,
			&i.NormalizedName,
			&i.NormalizedTag,
			&i.ProfileIconID,
			&i.Level,
			&i.SearchString,
			&i.SoloRank,
			&i.SoloTier,
			&i.SoloLp,
			&i.SoloRankPower,
			&i.SoloWins,
			&i.SoloLosses,
			&i.FlexRank,
			&i.FlexTier,
			&i.FlexLp,
			&i.FlexWins,
			&i.FlexLosses,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChampions = `-- name: ListChampions :many
SELECT id, slug, name, title, img_url, skills, patch, updated_at FROM lol_champions ORDER BY name
`

func (q *Queries) ListChampions(ctx context.Context) ([]LolChampion, error) {
	rows, err := q.db.Query(ctx, listChampions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolChampion
	for rows.Next() {
		var i LolChampion
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Title,
			&i.ImgUrl,
			&i.Skills,
			&i.Patch,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, name, plaintext, type, gold_total, from_items, into_items, is_summoners_rift, img_url, patch, updated_at FROM lol_items ORDER BY id
`

func (q *Queries) ListItems(ctx context.Context) ([]LolItem, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolItem
	for rows.Next() {
		var i LolItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Plaintext,
			&i.Type,
			&i.GoldTotal,
			&i.FromItems,
			&i.IntoItems,
			&i.IsSummonersRift,
			&i.ImgUrl,
			&i.Patch,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunes = `-- name: ListRunes :many
SELECT id, style_id, slot, sort_order, slug, name, short_desc, img_url, patch, updated_at FROM lol_runes ORDER BY style_id NULLS FIRST, slot NULLS FIRST, sort_order
`

// Cây trước, rồi tới rune của từng cây theo đúng thứ tự hàng; trong 1 hàng theo thứ tự trong game.
func (q *Queries) ListRunes(ctx context.Context) ([]LolRune, error) {
	rows, err := q.db.Query(ctx, listRunes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolRune
	for rows.Next() {
		var i LolRune
		if err := rows.Scan(
			&i.ID,
			&i.StyleID,
			&i.Slot,
			&i.SortOrder,
			&i.Slug,
			&i.Name,
			&i.ShortDesc,
			&i.ImgUrl,
			&i.Patch,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpells = `-- name: ListSpells :many
SELECT id, slug, name, description, img_url, patch, updated_at FROM lol_spells ORDER BY id
`

func (q *Queries) ListSpells(ctx context.Context) ([]LolSpell, error) {
	rows, err := q.db.Query(ctx, listSpells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolSpell
	for rows.Next() {
		var i LolSpell
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ImgUrl,
			&i.Patch,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshChampionBans = `-- name: RefreshChampionBans :exec
INSERT INTO lol_champion_bans (meta_id, champion_id, bans, ban_rate)
SELECT $1::uuid, ban.champion_id, count(*),
       count(*)::float8 / nullif($2::int, 0)
FROM (
    SELECT unnest(m.banned_champion_ids) AS champion_id
    FROM lol_matches m
    WHERE m.patch = $3::text
      AND m.mode = 'SOLO'
      AND NOT m.is_remake
      AND m.duration_sec >= $4::int
      AND m.estimated_rank = ANY($5::text[])
      AND ($6::text = 'GLOBAL' OR m.server = $6::text)
) ban
WHERE ban.champion_id >= 0
GROUP BY ban.champion_id
`

type RefreshChampionBansParams struct {
	MetaID       pgtype.UUID `json:"metaId"`
	TotalMatches int32       `json:"totalMatches"`
	Patch        string      `json:"patch"`
	MinDuration  int32       `json:"minDuration"`
	Ranks        []string    `json:"ranks"`
	Server       string      `json:"server"`
}

// Ban ở cấp trận: unnest banned_champion_ids (đã bỏ -1 lúc lưu).
func (q *Queries) RefreshChampionBans(ctx context.Context, arg RefreshChampionBansParams) error {
	_, err := q.db.Exec(ctx, refreshChampionBans,
		arg.MetaID,
		arg.TotalMatches,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	return err
}

const refreshChampionStatsBootItems = `-- name: RefreshChampionStatsBootItems :exec
WITH item_rows AS (
    SELECT p.position, p.champion_id, p.is_win, it.id AS item_id
    FROM lol_match_participants p
    JOIN lol_matches m ON m.id = p.match_id
    CROSS JOIN LATERAL unnest(p.items || p.role_bound_item) AS iid
    JOIN lol_items it
        ON it.id = COALESCE(($2::int[])[array_position($3::int[], iid)], iid)
       AND it.type = 'BOOTS'
    WHERE m.patch = $4::text
      AND m.mode = 'SOLO'
      AND NOT m.is_remake
      AND m.duration_sec >= $5::int
      AND m.estimated_rank = ANY($6::text[])
      AND ($7::text = 'GLOBAL' OR m.server = $7::text)
      AND p.position <> 'UNK'
),
agg AS (
    SELECT position, champion_id, item_id,
           count(*) AS games,
           count(*) FILTER (WHERE is_win) AS wins
    FROM item_rows
    GROUP BY position, champion_id, item_id
)
UPDATE lol_champion_stats cs
SET best_boot_items = sub.arr
FROM (
    SELECT position, champion_id,
           jsonb_agg(jsonb_build_object(
               'itemId', item_id, 'games', games, 'wins', wins
           ) ORDER BY games DESC) AS arr
    FROM agg
    GROUP BY position, champion_id
) sub
WHERE cs.meta_id = $1::uuid
  AND cs.position = sub.position
  AND cs.champion_id = sub.champion_id
`

type RefreshChampionStatsBootItemsParams struct {
	MetaID         pgtype.UUID `json:"metaId"`
	BaseIds        []int32     `json:"baseIds"`
	TransformedIds []int32     `json:"transformedIds"`
	Patch          string      `json:"patch"`
	MinDuration    int32       `json:"minDuration"`
	Ranks          []string    `json:"ranks"`
	Server         string      `json:"server"`
}

// Giày: xét cả role_bound_item vì giày ADC nằm ở ô riêng đó chứ không trong items. Giày tier 3
// gộp về giày tier 2 theo cặp transformed_ids[i] => base_ids[i] app truyền vào (cùng khuôn legendary).
func (q *Queries) RefreshChampionStatsBootItems(ctx context.Context, arg RefreshChampionStatsBootItemsParams) error {
	_, err := q.db.Exec(ctx, refreshChampionStatsBootItems,
		arg.MetaID,
		arg.BaseIds,
		arg.TransformedIds,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	return err
}

const refreshChampionStatsFirstLegendItems = `-- name: RefreshChampionStatsFirstLegendItems :exec
WITH mp AS (
    SELECT p.position, p.champion_id, p.is_win, p.first_legend_item AS item_id
    FROM lol_match_participants p
    JOIN lol_matches m ON m.id = p.match_id
    WHERE m.patch = $2::text
      AND m.mode = 'SOLO'
      AND NOT m.is_remake
      AND m.duration_sec >= $3::int
      AND m.estimated_rank = ANY($4::text[])
      AND ($5::text = 'GLOBAL' OR m.server = $5::text)
      AND p.position <> 'UNK'
      AND p.first_legend_item <> 0
),
agg AS (
    SELECT position, champion_id, item_id,
           count(*) AS games,
           count(*) FILTER (WHERE is_win) AS wins
    FROM mp
    GROUP BY position, champion_id, item_id
)
UPDATE lol_champion_stats cs
SET best_first_legend_items = sub.arr
FROM (
    SELECT position, champion_id,
           jsonb_agg(jsonb_build_object(
               'itemId', item_id, 'games', games, 'wins', wins
           ) ORDER BY games DESC) AS arr
    FROM agg
    GROUP BY position, champion_id
) sub
WHERE cs.meta_id = $1::uuid
  AND cs.position = sub.position
  AND cs.champion_id = sub.champion_id
`

type RefreshChampionStatsFirstLegendItemsParams struct {
	MetaID      pgtype.UUID `json:"metaId"`
	Patch       string      `json:"patch"`
	MinDuration int32       `json:"minDuration"`
	Ranks       []string    `json:"ranks"`
	Server      string      `json:"server"`
}

// Đồ legendary hoàn thành đầu tiên.
func (q *Queries) RefreshChampionStatsFirstLegendItems(ctx context.Context, arg RefreshChampionStatsFirstLegendItemsParams) error {
	_, err := q.db.Exec(ctx, refreshChampionStatsFirstLegendItems,
		arg.MetaID,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	return err
}

const refreshChampionStatsFirstThreeItems = `-- name: RefreshChampionStatsFirstThreeItems :exec
WITH mp AS (
    SELECT p.position, p.champion_id, p.is_win, p.legend_items_purchased[1:3] AS item_ids
    FROM lol_match_participants p
    JOIN lol_matches m ON m.id = p.match_id
    WHERE m.patch = $2::text
      AND m.mode = 'SOLO'
      AND NOT m.is_remake
      AND m.duration_sec >= $3::int
      AND m.estimated_rank = ANY($4::text[])
      AND ($5::text = 'GLOBAL' OR m.server = $5::text)
      AND p.position <> 'UNK'
      AND cardinality(p.legend_items_purchased) >= 3
),
agg AS (
    SELECT position, champion_id, item_ids,
           count(*) AS games,
           count(*) FILTER (WHERE is_win) AS wins
    FROM mp
    GROUP BY position, champion_id, item_ids
)
UPDATE lol_champion_stats cs
SET best_first_three_items = sub.arr
FROM (
    SELECT position, champion_id,
           jsonb_agg(jsonb_build_object(
               'itemIds', to_jsonb(item_ids), 'games', games, 'wins', wins
           ) ORDER BY games DESC) AS arr
    FROM agg
    GROUP BY position, champion_id
) sub
WHERE cs.meta_id = $1::uuid
  AND cs.position = sub.position
  AND cs.champion_id = sub.champion_id
`

type RefreshChampionStatsFirstThreeItemsParams struct {
	MetaID      pgtype.UUID `json:"metaId"`
	Patch       string      `json:"patch"`
	MinDuration int32       `json:"minDuration"`
	Ranks       []string    `json:"ranks"`
	Server      string      `json:"server"`
}

// 3 đồ legendary đầu, GIỮ thứ tự mua (A>B>C khác B>A>C).
func (q *Queries) RefreshChampionStatsFirstThreeItems(ctx context.Context, arg RefreshChampionStatsFirstThreeItemsParams) error {
	_, err := q.db.Exec(ctx, refreshChampionStatsFirstThreeItems,
		arg.MetaID,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	return err
}

const refreshChampionStatsLegendaryItems = `-- name: RefreshChampionStatsLegendaryItems :exec
WITH item_rows AS (
    SELECT p.position, p.champion_id, p.is_win, it.id AS item_id
    FROM lol_match_participants p
    JOIN lol_matches m ON m.id = p.match_id
    CROSS JOIN LATERAL unnest(p.items) AS iid
    -- iid không có trong transformed_ids => array_position NULL => phần tử NULL => giữ iid.
    JOIN lol_items it
        ON it.id = COALESCE(($2::int[])[array_position($3::int[], iid)], iid)
       AND it.type = 'LEGENDARY'
    WHERE m.patch = $4::text
      AND m.mode = 'SOLO'
      AND NOT m.is_remake
      AND m.duration_sec >= $5::int
      AND m.estimated_rank = ANY($6::text[])
      AND ($7::text = 'GLOBAL' OR m.server = $7::text)
      AND p.position <> 'UNK'
),
agg AS (
    SELECT position, champion_id, item_id,
           count(*) AS games,
           count(*) FILTER (WHERE is_win) AS wins
    FROM item_rows
    GROUP BY position, champion_id, item_id
)
UPDATE lol_champion_stats cs
SET best_legendary_items = sub.arr
FROM (
    SELECT position, champion_id,
           jsonb_agg(jsonb_build_object(
               'itemId', item_id, 'games', games, 'wins', wins
           ) ORDER BY games DESC) AS arr
    FROM agg
    GROUP BY position, champion_id
) sub
WHERE cs.meta_id = $1::uuid
  AND cs.position = sub.position
  AND cs.champion_id = sub.champion_id
`

type RefreshChampionStatsLegendaryItemsParams struct {
	MetaID         pgtype.UUID `json:"metaId"`
	BaseIds        []int32     `json:"baseIds"`
	TransformedIds []int32     `json:"transformedIds"`
	Patch          string      `json:"patch"`
	MinDuration    int32       `json:"minDuration"`
	Ranks          []string    `json:"ranks"`
	Server         string      `json:"server"`
}

// Item legendary: unnest items rồi lọc theo lol_items.type. Item biến đổi (Muramana...) gộp về
// item gốc (Manamune...) theo cặp transformed_ids[i] => base_ids[i] app truyền vào.
func (q *Queries) RefreshChampionStatsLegendaryItems(ctx context.Context, arg RefreshChampionStatsLegendaryItemsParams) error {
	_, err := q.db.Exec(ctx, refreshChampionStatsLegendaryItems,
		arg.MetaID,
		arg.BaseIds,
		arg.TransformedIds,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	return err
}

const refreshChampionStatsMatchups = `-- name: RefreshChampionStatsMatchups :exec
WITH mp AS (
    SELECT p.match_id, p.team, p.position, p.champion_id, p.is_win
    FROM lol_match_participants p
    JOIN lol_matches m ON m.id = p.match_id
    WHERE m.patch = $2::text
      AND m.mode = 'SOLO'
      AND NOT m.is_remake
      AND m.duration_sec >= $3::int
      AND m.estimated_rank = ANY($4::text[])
      AND ($5::text = 'GLOBAL' OR m.server = $5::text)
      AND p.position <> 'UNK'
),
pairs AS (
    SELECT me.position, me.champion_id, opp.champion_id AS opponent_champion_id, me.is_win
    FROM mp me
    JOIN mp opp ON opp.match_id = me.match_id AND opp.position = me.position AND opp.team <> me.team
),
agg AS (
    SELECT position, champion_id, opponent_champion_id,
           count(*) AS games,
           count(*) FILTER (WHERE is_win) AS wins
    FROM pairs
    GROUP BY position, champion_id, opponent_champion_id
)
UPDATE lol_champion_stats cs
SET best_match_ups = sub.arr
FROM (
    SELECT position, champion_id,
           jsonb_agg(jsonb_build_object(
               'opponentChampionId', opponent_champion_id, 'games', games, 'wins', wins
           ) ORDER BY games DESC) AS arr
    FROM agg
    GROUP BY position, champion_id
) sub
WHERE cs.meta_id = $1::uuid
  AND cs.position = sub.position
  AND cs.champion_id = sub.champion_id
`

type RefreshChampionStatsMatchupsParams struct {
	MetaID      pgtype.UUID `json:"metaId"`
	Patch       string      `json:"patch"`
	MinDuration int32       `json:"minDuration"`
	Ranks       []string    `json:"ranks"`
	Server      string      `json:"server"`
}

// Matchup: self-join participant cùng match, cùng position, khác phe.
func (q *Queries) RefreshChampionStatsMatchups(ctx context.Context, arg RefreshChampionStatsMatchupsParams) error {
	_, err := q.db.Exec(ctx, refreshChampionStatsMatchups,
		arg.MetaID,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	return err
}

const refreshChampionStatsRunes = `-- name: RefreshChampionStatsRunes :exec
WITH mp AS (
    SELECT p.position, p.champion_id, p.is_win,
           p.rune_primary_style, p.rune_sub_style, p.key_rune, p.runes, p.stat_runes
    FROM lol_match_participants p
    JOIN lol_matches m ON m.id = p.match_id
    WHERE m.patch = $2::text
      AND m.mode = 'SOLO'
      AND NOT m.is_remake
      AND m.duration_sec >= $3::int
      AND m.estimated_rank = ANY($4::text[])
      AND ($5::text = 'GLOBAL' OR m.server = $5::text)
      AND p.position <> 'UNK'
),
agg AS (
    SELECT position, champion_id, rune_primary_style, rune_sub_style, key_rune, runes, stat_runes,
           count(*) AS games,
           count(*) FILTER (WHERE is_win) AS wins
    FROM mp
    GROUP BY position, champion_id, rune_primary_style, rune_sub_style, key_rune, runes, stat_runes
)
UPDATE lol_champion_stats cs
SET best_runes = sub.arr
FROM (
    SELECT position, champion_id,
           jsonb_agg(jsonb_build_object(
               'runePrimaryStyle', rune_primary_style, 'runeSubStyle', rune_sub_style,
               'keyRune', key_rune, 'runes', to_jsonb(runes), 'statRunes', to_jsonb(stat_runes),
               'games', games, 'wins', wins
           ) ORDER BY games DESC) AS arr
    FROM agg
    GROUP BY position, champion_id
) sub
WHERE cs.meta_id = $1::uuid
  AND cs.position = sub.position
  AND cs.champion_id = sub.champion_id
`

type RefreshChampionStatsRunesParams struct {
	MetaID      pgtype.UUID `json:"metaId"`
	Patch       string      `json:"patch"`
	MinDuration int32       `json:"minDuration"`
	Ranks       []string    `json:"ranks"`
	Server      string      `json:"server"`
}

func (q *Queries) RefreshChampionStatsRunes(ctx context.Context, arg RefreshChampionStatsRunesParams) error {
	_, err := q.db.Exec(ctx, refreshChampionStatsRunes,
		arg.MetaID,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	return err
}

const refreshChampionStatsScalars = `-- name: RefreshChampionStatsScalars :exec
INSERT INTO lol_champion_stats (
    meta_id, position, champion_id, champion_slug,
    games, wins, win_rate, pick_rate,
    avg_kills, avg_deaths, avg_assists, avg_kda, avg_kp,
    avg_cs_per_min, avg_gold_per_min, avg_dmg_per_min, avg_dmg_taken_per_min, avg_cc_per_min,
    avg_physical_dmg, avg_magic_dmg, avg_true_dmg,
    avg_penta, avg_solo_kills, avg_perf_score
)
SELECT
    $1::uuid, mp.position, mp.champion_id, max(mp.champion_slug),
    count(*),
    count(*) FILTER (WHERE mp.is_win),
    count(*) FILTER (WHERE mp.is_win)::float8 / count(*),
    count(*)::float8 / nullif($2::int, 0),
    avg(mp.kills), avg(mp.deaths), avg(mp.assists), avg(mp.kda), avg(mp.kill_participation),
    avg(mp.cs_per_min), avg(mp.gold_per_min), avg(mp.dmg_per_min), avg(mp.dmg_taken_per_min), avg(mp.cc_per_min),
    avg(mp.physical_dmg_dealt), avg(mp.magic_dmg_dealt), avg(mp.true_dmg_dealt),
    avg(mp.penta_kills), avg(mp.solo_kills), avg(mp.perf_score)
FROM (
    SELECT p.match_id, p.team, p.is_win, p.player_id, p.participant_id, p.name, p.tag, p.rank_power, p.champion_id, p.champion_slug, p.champ_level, p.position, p.kills, p.deaths, p.assists, p.kda, p.kill_participation, p.double_kills, p.triple_kills, p.quadra_kills, p.penta_kills, p.solo_kills, p.gold, p.gold_per_min, p.minions_killed, p.neutral_minions_killed, p.cs, p.cs_per_min, p.dmg_dealt, p.dmg_per_min, p.physical_dmg_dealt, p.magic_dmg_dealt, p.true_dmg_dealt, p.dmg_to_turrets, p.dmg_taken, p.dmg_taken_per_min, p.crowd_control, p.cc_per_min, p.heal, p.heal_others, p.shield_others, p.vision_score, p.wards_placed, p.wards_killed, p.perf_score, p.spell1_id, p.spell2_id, p.rune_primary_style, p.rune_sub_style, p.key_rune, p.runes, p.stat_runes, p.items, p.role_bound_item, p.starter_sets, p.skills_leveled, p.first_legend_item, p.legend_items_purchased
    FROM lol_match_participants p
    JOIN lol_matches m ON m.id = p.match_id
    WHERE m.patch = $3::text
      AND m.mode = 'SOLO'
      AND NOT m.is_remake
      AND m.duration_sec >= $4::int
      AND m.estimated_rank = ANY($5::text[])
      AND ($6::text = 'GLOBAL' OR m.server = $6::text)
      AND p.position <> 'UNK'
) mp
GROUP BY mp.position, mp.champion_id
`

type RefreshChampionStatsScalarsParams struct {
	MetaID       pgtype.UUID `json:"metaId"`
	TotalMatches int32       `json:"totalMatches"`
	Patch        string      `json:"patch"`
	MinDuration  int32       `json:"minDuration"`
	Ranks        []string    `json:"ranks"`
	Server       string      `json:"server"`
}

// Scalar aggregate. Cột JSONB để DEFAULT '[]', các query Refresh...* bên dưới điền sau.
// avg_x lưu trung bình có trọng số theo participant; gộp nhiều dòng sau này dùng SUM(avg_x*games)/SUM(games).
func (q *Queries) RefreshChampionStatsScalars(ctx context.Context, arg RefreshChampionStatsScalarsParams) error {
	_, err := q.db.Exec(ctx, refreshChampionStatsScalars,
		arg.MetaID,
		arg.TotalMatches,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	return err
}

const refreshChampionStatsSkillsLeveled = `-- name: RefreshChampionStatsSkillsLeveled :exec
WITH mp AS (
    SELECT p.position, p.champion_id, p.is_win, p.skills_leveled[1:13] AS skills
    FROM lol_match_participants p
    JOIN lol_matches m ON m.id = p.match_id
    WHERE m.patch = $2::text
      AND m.mode = 'SOLO'
      AND NOT m.is_remake
      AND m.duration_sec >= $3::int
      AND m.estimated_rank = ANY($4::text[])
      AND ($5::text = 'GLOBAL' OR m.server = $5::text)
      AND p.position <> 'UNK'
      AND cardinality(p.skills_leveled) >= 13
),
agg AS (
    SELECT position, champion_id, skills,
           count(*) AS games,
           count(*) FILTER (WHERE is_win) AS wins
    FROM mp
    GROUP BY position, champion_id, skills
)
UPDATE lol_champion_stats cs
SET best_skills_leveled = sub.arr
FROM (
    SELECT position, champion_id,
           jsonb_agg(jsonb_build_object(
               'skills', to_jsonb(skills), 'games', games, 'wins', wins
           ) ORDER BY games DESC) AS arr
    FROM agg
    GROUP BY position, champion_id
) sub
WHERE cs.meta_id = $1::uuid
  AND cs.position = sub.position
  AND cs.champion_id = sub.champion_id
`

type RefreshChampionStatsSkillsLeveledParams struct {
	MetaID      pgtype.UUID `json:"metaId"`
	Patch       string      `json:"patch"`
	MinDuration int32       `json:"minDuration"`
	Ranks       []string    `json:"ranks"`
	Server      string      `json:"server"`
}

// Gộp theo 13 lần lên skill đầu: vừa đủ max 2 skill thường, phần sau phân mảnh theo độ dài trận.
func (q *Queries) RefreshChampionStatsSkillsLeveled(ctx context.Context, arg RefreshChampionStatsSkillsLeveledParams) error {
	_, err := q.db.Exec(ctx, refreshChampionStatsSkillsLeveled,
		arg.MetaID,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	return err
}

const refreshChampionStatsSpellCombos = `-- name: RefreshChampionStatsSpellCombos :exec
WITH mp AS (
    SELECT p.position, p.champion_id, p.is_win, p.spell1_id, p.spell2_id
    FROM lol_match_participants p
    JOIN lol_matches m ON m.id = p.match_id
    WHERE m.patch = $2::text
      AND m.mode = 'SOLO'
      AND NOT m.is_remake
      AND m.duration_sec >= $3::int
      AND m.estimated_rank = ANY($4::text[])
      AND ($5::text = 'GLOBAL' OR m.server = $5::text)
      AND p.position <> 'UNK'
),
agg AS (
    SELECT position, champion_id, spell1_id, spell2_id,
           count(*) AS games,
           count(*) FILTER (WHERE is_win) AS wins
    FROM mp
    GROUP BY position, champion_id, spell1_id, spell2_id
)
UPDATE lol_champion_stats cs
SET best_spell_combos = sub.arr
FROM (
    SELECT position, champion_id,
           jsonb_agg(jsonb_build_object(
               'spell1Id', spell1_id, 'spell2Id', spell2_id, 'games', games, 'wins', wins
           ) ORDER BY games DESC) AS arr
    FROM agg
    GROUP BY position, champion_id
) sub
WHERE cs.meta_id = $1::uuid
  AND cs.position = sub.position
  AND cs.champion_id = sub.champion_id
`

type RefreshChampionStatsSpellCombosParams struct {
	MetaID      pgtype.UUID `json:"metaId"`
	Patch       string      `json:"patch"`
	MinDuration int32       `json:"minDuration"`
	Ranks       []string    `json:"ranks"`
	Server      string      `json:"server"`
}

func (q *Queries) RefreshChampionStatsSpellCombos(ctx context.Context, arg RefreshChampionStatsSpellCombosParams) error {
	_, err := q.db.Exec(ctx, refreshChampionStatsSpellCombos,
		arg.MetaID,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	return err
}

const refreshChampionStatsStarterSets = `-- name: RefreshChampionStatsStarterSets :exec
WITH mp AS (
    SELECT p.position, p.champion_id, p.is_win, p.starter_sets AS item_ids
    FROM lol_match_participants p
    JOIN lol_matches m ON m.id = p.match_id
    WHERE m.patch = $2::text
      AND m.mode = 'SOLO'
      AND NOT m.is_remake
      AND m.duration_sec >= $3::int
      AND m.estimated_rank = ANY($4::text[])
      AND ($5::text = 'GLOBAL' OR m.server = $5::text)
      AND p.position <> 'UNK'
      AND cardinality(p.starter_sets) > 0
),
agg AS (
    SELECT position, champion_id, item_ids,
           count(*) AS games,
           count(*) FILTER (WHERE is_win) AS wins
    FROM mp
    GROUP BY position, champion_id, item_ids
)
UPDATE lol_champion_stats cs
SET best_starter_sets = sub.arr
FROM (
    SELECT position, champion_id,
           jsonb_agg(jsonb_build_object(
               'itemIds', to_jsonb(item_ids), 'games', games, 'wins', wins
           ) ORDER BY games DESC) AS arr
    FROM agg
    GROUP BY position, champion_id
) sub
WHERE cs.meta_id = $1::uuid
  AND cs.position = sub.position
  AND cs.champion_id = sub.champion_id
`

type RefreshChampionStatsStarterSetsParams struct {
	MetaID      pgtype.UUID `json:"metaId"`
	Patch       string      `json:"patch"`
	MinDuration int32       `json:"minDuration"`
	Ranks       []string    `json:"ranks"`
	Server      string      `json:"server"`
}

// Các cột từ timeline: chỉ tính participant có dữ liệu tương ứng (không có timeline => mảng rỗng / 0).
// Starter set đã sort lúc lưu nên GROUP BY thẳng mảng.
func (q *Queries) RefreshChampionStatsStarterSets(ctx context.Context, arg RefreshChampionStatsStarterSetsParams) error {
	_, err := q.db.Exec(ctx, refreshChampionStatsStarterSets,
		arg.MetaID,
		arg.Patch,
		arg.MinDuration,
		arg.Ranks,
		arg.Server,
	)
	return err
}

const searchPlayers = `-- name: SearchPlayers :many
SELECT id, server, name, tag, normalized_name, normalized_tag, profile_icon_id, level, search_string, solo_rank, solo_tier, solo_lp, solo_rank_power, solo_wins, solo_losses, flex_rank, flex_tier, flex_lp, flex_wins, flex_losses, created_at, updated_at FROM lol_players
WHERE name ILIKE '%' || $1::text || '%'
   OR tag ILIKE '%' || $1::text || '%'
   OR search_string LIKE '%' || $2::text || '%'
ORDER BY solo_rank_power DESC NULLS LAST
LIMIT $3
`

type SearchPlayersParams struct {
	Keyword           string `json:"keyword"`
	NormalizedKeyword string `json:"normalizedKeyword"`
	Lim               int32  `json:"lim"`
}

func (q *Queries) SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]LolPlayer, error) {
	rows, err := q.db.Query(ctx, searchPlayers, arg.Keyword, arg.NormalizedKeyword, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LolPlayer
	for rows.Next() {
		var i LolPlayer
		if err := rows.Scan(
			&i.ID,
			&i.Server,
			&i.Name,
			&i.Tag,
			&i.NormalizedName,
			&i.NormalizedTag,
			&i.ProfileIconID,
			&i.Level,
			&i.SearchString,
			&i.SoloRank,
			&i.SoloTier,
			&i.SoloLp,
			&i.SoloRankPower,
			&i.SoloWins,
			&i.SoloLosses,
			&i.FlexRank,
			&i.FlexTier,
			&i.FlexLp,
			&i.FlexWins,
			&i.FlexLosses,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChampion = `-- name: UpsertChampion :exec
INSERT INTO lol_champions (id, slug, name, title, img_url, skills, patch)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    slug       = EXCLUDED.slug,
    name       = EXCLUDED.name,
    title      = EXCLUDED.title,
    img_url    = EXCLUDED.img_url,
    skills     = EXCLUDED.skills,
    patch      = EXCLUDED.patch,
    updated_at = now()
`

type UpsertChampionParams struct {
	ID     int32  `json:"id"`
	Slug   string `json:"slug"`
	Name   string `json:"name"`
	Title  string `json:"title"`
	ImgUrl string `json:"imgUrl"`
	Skills []byte `json:"skills"`
	Patch  string `json:"patch"`
}

func (q *Queries) UpsertChampion(ctx context.Context, arg UpsertChampionParams) error {
	_, err := q.db.Exec(ctx, upsertChampion,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Title,
		arg.ImgUrl,
		arg.Skills,
		arg.Patch,
	)
	return err
}

const upsertItem = `-- name: UpsertItem :exec
INSERT INTO lol_items (id, name, plaintext, type, gold_total, from_items, into_items, is_summoners_rift, img_url, patch)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
    name       = EXCLUDED.name,
    plaintext  = EXCLUDED.plaintext,
    type       = EXCLUDED.type,
    gold_total = EXCLUDED.gold_total,
    from_items = EXCLUDED.from_items,
    into_items = EXCLUDED.into_items,
    is_summoners_rift = EXCLUDED.is_summoners_rift,
    img_url    = EXCLUDED.img_url,
    patch      = EXCLUDED.patch,
    updated_at = now()
`

type UpsertItemParams struct {
	ID              int32   `json:"id"`
	Name            string  `json:"name"`
	Plaintext       string  `json:"plaintext"`
	Type            string  `json:"type"`
	GoldTotal       int32   `json:"goldTotal"`
	FromItems       []int32 `json:"fromItems"`
	IntoItems       []int32 `json:"intoItems"`
	IsSummonersRift bool    `json:"isSummonersRift"`
	ImgUrl          string  `json:"imgUrl"`
	Patch           string  `json:"patch"`
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) error {
	_, err := q.db.Exec(ctx, upsertItem,
		arg.ID,
		arg.Name,
		arg.Plaintext,
		arg.Type,
		arg.GoldTotal,
		arg.FromItems,
		arg.IntoItems,
		arg.IsSummonersRift,
		arg.ImgUrl,
		arg.Patch,
	)
	return err
}

const upsertMeta = `-- name: UpsertMeta :one
INSERT INTO lol_metas (patch, server, rank_bucket, total_matches)
VALUES ($1::text, $2::text, $3::text, $4::int)
ON CONFLICT (patch, server, rank_bucket) DO UPDATE SET
    total_matches = EXCLUDED.total_matches,
    updated_at    = now()
RETURNING id
`

type UpsertMetaParams struct {
	Patch        string `json:"patch"`
	Server       string `json:"server"`
	RankBucket   string `json:"rankBucket"`
	TotalMatches int32  `json:"totalMatches"`
}

// Upsert theo khóa tự nhiên: id giữ nguyên qua mỗi lần refresh.
func (q *Queries) UpsertMeta(ctx context.Context, arg UpsertMetaParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertMeta,
		arg.Patch,
		arg.Server,
		arg.RankBucket,
		arg.TotalMatches,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertPlayer = `-- name: UpsertPlayer :exec
INSERT INTO lol_players (
    id, server, name, tag, normalized_name, normalized_tag, profile_icon_id, level, search_string,
    solo_rank, solo_tier, solo_lp, solo_rank_power, solo_wins, solo_losses,
    flex_rank, flex_tier, flex_lp, flex_wins, flex_losses
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
ON CONFLICT (id) DO UPDATE SET
    server          = EXCLUDED.server,
    name            = EXCLUDED.name,
    tag             = EXCLUDED.tag,
    normalized_name = EXCLUDED.normalized_name,
    normalized_tag  = EXCLUDED.normalized_tag,
    profile_icon_id = COALESCE(EXCLUDED.profile_icon_id, lol_players.profile_icon_id),
    level           = COALESCE(EXCLUDED.level, lol_players.level),
    search_string   = EXCLUDED.search_string,

    solo_rank       = COALESCE(EXCLUDED.solo_rank, lol_players.solo_rank),
    solo_tier       = CASE WHEN EXCLUDED.solo_rank IS NULL THEN lol_players.solo_tier       ELSE EXCLUDED.solo_tier       END,
    solo_lp         = CASE WHEN EXCLUDED.solo_rank IS NULL THEN lol_players.solo_lp         ELSE EXCLUDED.solo_lp         END,
    solo_rank_power = CASE WHEN EXCLUDED.solo_rank IS NULL THEN lol_players.solo_rank_power ELSE EXCLUDED.solo_rank_power END,
    solo_wins       = CASE WHEN EXCLUDED.solo_rank IS NULL THEN lol_players.solo_wins       ELSE EXCLUDED.solo_wins       END,
    solo_losses     = CASE WHEN EXCLUDED.solo_rank IS NULL THEN lol_players.solo_losses     ELSE EXCLUDED.solo_losses     END,

    flex_rank       = COALESCE(EXCLUDED.flex_rank, lol_players.flex_rank),
    flex_tier       = CASE WHEN EXCLUDED.flex_rank IS NULL THEN lol_players.flex_tier   ELSE EXCLUDED.flex_tier   END,
    flex_lp         = CASE WHEN EXCLUDED.flex_rank IS NULL THEN lol_players.flex_lp     ELSE EXCLUDED.flex_lp     END,
    flex_wins       = CASE WHEN EXCLUDED.flex_rank IS NULL THEN lol_players.flex_wins   ELSE EXCLUDED.flex_wins   END,
    flex_losses     = CASE WHEN EXCLUDED.flex_rank IS NULL THEN lol_players.flex_losses ELSE EXCLUDED.flex_losses END,

    updated_at      = now()
`

type UpsertPlayerParams struct {
	ID             string      `json:"id"`
	Server         string      `json:"server"`
	Name           string      `json:"name"`
	Tag            string      `json:"tag"`
	NormalizedName string      `json:"normalizedName"`
	NormalizedTag  string      `json:"normalizedTag"`
	ProfileIconID  pgtype.Int4 `json:"profileIconId"`
	Level          pgtype.Int4 `json:"level"`
	SearchString   string      `json:"searchString"`
	SoloRank       pgtype.Text `json:"soloRank"`
	SoloTier       pgtype.Text `json:"soloTier"`
	SoloLp         int32       `json:"soloLp"`
	SoloRankPower  pgtype.Int4 `json:"soloRankPower"`
	SoloWins       int32       `json:"soloWins"`
	SoloLosses     int32       `json:"soloLosses"`
	FlexRank       pgtype.Text `json:"flexRank"`
	FlexTier       pgtype.Text `json:"flexTier"`
	FlexLp         int32       `json:"flexLp"`
	FlexWins       int32       `json:"flexWins"`
	FlexLosses     int32       `json:"flexLosses"`
}

// Rank solo/flex truyền vào NULL (unknown) thì giữ nguyên cả nhóm cột rank cũ.
func (q *Queries) UpsertPlayer(ctx context.Context, arg UpsertPlayerParams) error {
	_, err := q.db.Exec(ctx, upsertPlayer,
		arg.ID,
		arg.Server,
		arg.Name,
		arg.Tag,
		arg.NormalizedName,
		arg.NormalizedTag,
		arg.ProfileIconID,
		arg.Level,
		arg.SearchString,
		arg.SoloRank,
		arg.SoloTier,
		arg.SoloLp,
		arg.SoloRankPower,
		arg.SoloWins,
		arg.SoloLosses,
		arg.FlexRank,
		arg.FlexTier,
		arg.FlexLp,
		arg.FlexWins,
		arg.FlexLosses,
	)
	return err
}

const upsertRune = `-- name: UpsertRune :exec
INSERT INTO lol_runes (id, style_id, slot, sort_order, slug, name, short_desc, img_url, patch)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    style_id   = EXCLUDED.style_id,
    slot       = EXCLUDED.slot,
    sort_order = EXCLUDED.sort_order,
    slug       = EXCLUDED.slug,
    name       = EXCLUDED.name,
    short_desc = EXCLUDED.short_desc,
    img_url    = EXCLUDED.img_url,
    patch      = EXCLUDED.patch,
    updated_at = now()
`

type UpsertRuneParams struct {
	ID        int32       `json:"id"`
	StyleID   pgtype.Int4 `json:"styleId"`
	Slot      pgtype.Int4 `json:"slot"`
	SortOrder int32       `json:"sortOrder"`
	Slug      string      `json:"slug"`
	Name      string      `json:"name"`
	ShortDesc string      `json:"shortDesc"`
	ImgUrl    string      `json:"imgUrl"`
	Patch     string      `json:"patch"`
}

// Cây (style_id NULL) phải upsert trước rune của nó vì style_id tham chiếu ngược về chính bảng này.
func (q *Queries) UpsertRune(ctx context.Context, arg UpsertRuneParams) error {
	_, err := q.db.Exec(ctx, upsertRune,
		arg.ID,
		arg.StyleID,
		arg.Slot,
		arg.SortOrder,
		arg.Slug,
		arg.Name,
		arg.ShortDesc,
		arg.ImgUrl,
		arg.Patch,
	)
	return err
}

const upsertSpell = `-- name: UpsertSpell :exec
INSERT INTO lol_spells (id, slug, name, description, img_url, patch)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    slug        = EXCLUDED.slug,
    name        = EXCLUDED.name,
    description = EXCLUDED.description,
    img_url     = EXCLUDED.img_url,
    patch       = EXCLUDED.patch,
    updated_at  = now()
`

type UpsertSpellParams struct {
	ID          int32  `json:"id"`
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
	ImgUrl      string `json:"imgUrl"`
	Patch       string `json:"patch"`
}

func (q *Queries) UpsertSpell(ctx context.Context, arg UpsertSpellParams) error {
	_, err := q.db.Exec(ctx, upsertSpell,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ImgUrl,
		arg.Patch,
	)
	return err
}
